### ISSUE TITLE
SRS not available after Reader::prepare

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#1019]
`Reader::getSpatialReference` is empty after `Reader::prepare` is called.  However `Reader::preview` does populate an SRS.  Here's a [test file](https://github.com/hobu/greyhound/blob/master/examples/data/autzen.las) that shows the behavior.

Here's some [sample code and its output](https://gist.github.com/connormanning/dc4671db540c3087912f).

**Comment by abellgithub** [comment]
This is correct behavior.  A stage's spatial reference in a pipeline represents the spatial reference of a transformation.  Perhaps a reader's spatial reference should be set into the PointTable as soon as it is known, in which case PointTable::spatialRef() will return the value you desire.

**Comment by hobu** [comment]
> Perhaps a reader's spatial reference should be set into the PointTable as soon as it is known

I think that should be the case. Should we go through and update all the drivers to do so?

**Comment by abellgithub** [comment]
There WAS a reason things were done this way.  I'm trying to remember why.
I looked back through the history, but it came in with the LAS 1.4 merge
and the history there is gone or I can't figure out how to get it.  Perhaps
the reason is gone, and if so, I'd be all for moving things so that they
were all done in initialize(), but they were moved on purpose, and I
remember being unhappy about it at the time, but I don't remember the
reason.

We could just move things and see what breaks :)

On Thu, Oct 29, 2015 at 8:28 AM, Howard Butler <notifications@github.com>
wrote:

> Perhaps a reader's spatial reference should be set into the PointTable as
> soon as it is known
>
> I think that should be the case. Should we go through and update all the
> drivers to do so?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/1019#issuecomment-152178817>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by hobu** [comment]
> it came in with the LAS 1.4 merge and the history there is gone or I can't figure out how to get it.

Ah, I suppose this might be related to SRS info in EVLRs?

**Comment by abellgithub** [comment]
This is specific to implementation of the readers.  This has been fixed for LAS.  I'll check others when I can.

**Comment by hobu** [comment]
I assume this is all cleaned up now that PointView has an SRS.
