### ISSUE TITLE
Add python folder in build instruction

### ISSUE THREAD

**Issue by lucadelu** [PDAL/PDAL#1055]
If user run cmake enabling python with PDAL_HAVE_PYTHON=ON also the python folder should be compiled and installed.

Right now user has to run "python setup.py build && python setup.py install" by hand after pdal compilation.

**Comment by hobu** [comment]
> Right now user has to run "python setup.py build && python setup.py install" by hand after pdal compilation.

I always found this behavior of GDAL rather frustrating and hard to control. If you're using Python inside of a virtual environment or something, it's difficult to know at cmake time where to install things. You end up manually installing anyway. That's why the "use PDAL from Python" code is just an extension that can be easy_install'd at the moment. I'm not sure we should systemically fix this, but I agree the docs are weak and should be improved.
