### ISSUE TITLE
Support OGR in `filters.crop`

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1056]
WKT as the only geometry input mechanism is painful if all you have is a shapefile or something. It would be very handy to be able to define an OGR query that provides the polygons that are then used to crop the data.

**Comment by abellgithub** [comment]
As you might guess, I'm not a fan.  Rather than throw GDAL/OGR stuff all over, can we at least stick it in one place and convert if necessary to a single format? -- WKT, I suppose.  Let the filters in general only do one thing and if we need to use GDAL somewhere to convert, so be it, but it seems like it should be in options handling or someplace like that, not in filters themselves.  There must be a better way to do this in general.

**Comment by hobu** [comment]
> it seems like it should be in options handling or someplace like that, not in filters themselves.

Ok, I can get behind that. We would want OGR support in at least the following filters:

* `filters.crop`
* `filters.attribute`

I'm not quite sure how we can make it work though. There isn't a single "fetch this single geometry from a giant string of OGR definition" available to us in OGR land. All the stuff that `filters.attribute` supports is about the minimum it would need to define.
