### ISSUE TITLE
Numpy -> PDAL PointView

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#1573]
There is a mechanism in the PDAL Python extension to read a Pipeline and get back a Numpy array, but there isn't a `readers.numpy` capability to go the other way.

**Comment by chambbj** [comment]
I had always considered this being used to write the result of a python script that used the PDAL Python extension. I think that's a valid use case, but it also occurs to me now that it would be quite handy if one could use PDAL to read into the Numpy array, and then feed the resulting Numpy array back to PDAL stages one at a time to evaluate and tweak parameters individually, and then finally (optionally) writing the result. This could be a very powerful way to construct a pipeline from scratch and obviates the need to either 1) create a bunch of piecewise PDAL pipelines to process individual stages or 2) rerun the entire pipeline every time just to test a single stage in the context of the whole.

**Comment by abellgithub** [comment]
I don't understand. This is a testing thing? What are you wanting to test, exactly?

**Comment by chambbj** [comment]
No, I mean to incrementally build and step through a pipeline from Python.

**Comment by abellgithub** [comment]
This is what the Scala guys did, if I'm understanding you right. They didn't want to use JSON for some reason. It's...interesting.

**Comment by hobu** [comment]
In summary of the proposed workflow:

1) Invoke a simple pipeline
```
{
  "pipeline":[
    "input.las",
    {
      "type":"filters.range",
      "limits":"Z[0:10000]"
    },
    "output.las"
  ]
}
```

2. Invoke it in Python

```
import pdal
pipeline = pdal.Pipeline(json)
count = pipeline.execute()
arrays = pipeline.arrays
```

3. Create a filters-only pipeline
```
filters = """
[
    {
      "type":"filters.transformation",
      "matrix":" 0.886021478 -0.463609330 -0.005685887 1001.767853725 0.463642504 0.885984748 0.008164234 927.201546884 0.001252594 -0.009869906 0.999950507 514.513223273 0.000000000 0.000000000 0.000000000 1.000000000"
    },
    {
      "type":"filters.transformation",
      "matrix":"1.000000000 0.000000000 0.000000000 536000.000000000 0.000000000 1.000000000 0.000000000 7356000.000000000 0.000000000 0.000000000 1.000000000 0.000000000 0.000000000 0.000000000 0.000000000 1.000000000"
    },
    {
      "type":"filters.colorinterp",
      "ramp":"pestel_shades",
      "minimum":2000,
      "maximum":6000,
      "mad":true
    }
]
"""
```

4. Append it to the existing Python pipeline

```
pipeline.addStage(filters)
```

5. Re-execute and fetch the arrays

```
pipeline.execute()
arrays = pipeline.arrays
```

**Comment by chambbj** [comment]
I was thinking something more like the following. Steps one through three
are unchanged (though the writer is not always necessary). For step four,
instead of executing the whole pipeline again, feed a numpy array
(typically this would just be the output of step two, possibly modified,
maybe just inspected) to PDAL to run the filters only pipeline, and then
fetch the result again. That said, maybe it's not a filters only pipeline
at all. Maybe it's fed to a writer once you are happy with the result.

**Comment by chambbj** [comment]
Back at my keyboard now and a little easier to expand on the proposed usage a bit. For example, let's say that the user just wants to read his point cloud, and reset all classifications to start.

```python
import pdal

json = """{
  "pipeline":[
    "input.las",
    {
      "type":"filters.assign",
      "assignment":"Classification[:]=0"
    }
  ]
}"""

p = pdal.Pipeline(json)
p.validate()
count = p.execute()
data = p.arrays
```

With that out of the way, she continues to manipulate or simply inspect the data. This step is pretty loosely defined, but examples could include anything from filtering based on return number to computing statistics on a dimension to be used in setting downstream filter parameters.

As an example, let's pretend that she sees there are a significant number of high noise points through analyzing the distribution of the Z dimension. She decides that applying a range filter to passthrough `Z <= 200` would do a reasonable job of cleaning up this noise.

```python
filters = """[
  {
    "type":"filters.range",
    "limits":"Z(:200]"
  }
]"""

# And this is where the debate begins. Do we do something that continues
# processing the previously constructed pipeline?

p.addFilters(filters)
count = p.continue()
filtered_data = p.arrays

# Or create something new altogether?

s = pdal.Stage(data, filters)
s.validate()
count = s.execute()
filtered_data = s.arrays

# One could even imagine a world in which we could simply pass the Numpy
# array directly to the filter of choice. Though it's less clear to the user in this
# scenario how this translates to the JSON that would be needed in a
# repeatable pipeline.

filtered_data = pdal.filters.range(data, limits="Z(:200]")
```

No matter how you slice it, the hope would be that we could pick up from the previously processed Numpy array and apply just this stage, rather than going back to the original pipeline and rerunning **everything**.

Now, having written that, the passthrough example is perhaps a bad one because there are such easy ways to do this directly in Python, but the point here remains that you are going through this process in order to build a final JSON pipeline that can be applied to many datasets. And as @hobu guessed, another motivator would be that you could document all of this in a Jupyter notebook, stepping users through the stages of a pipeline to demonstrate and justify the stages and parameters used.

And this doesn't have to be a filters-only proposition. At the conclusion (or at any point really), the user should be able to write the data to disk.

```python
writer = """{
  "type":"writers.las",
  "filename":"output.laz",
  "compressed":true
}"""

# Validate and execute with a TBD set of commands.

w = pdal.Stage(data, writers)
w.validate()
count = w.execute()
```

So all of this seems quite possible if we had a `readers.numpy` or similar so that we could construct a pipeline on-the-fly using the requested stages and the supplied Numpy array. As discussed, this does mean copying data each time.

**Comment by abellgithub** [comment]
This was completed in 1.5 or 1.6
