### ISSUE TITLE
PDAL Reader.las and Writer.las error

### ISSUE THREAD

**Issue by ahmadshabbir99** [PDAL/PDAL#1629]
I am trying to read and write LAS (*.las) file using PDAL but getting the following warning messages and the reading and writing is not being done correctly by PDAL reader and writer for las files.

(pdal pipeline readers.las Warning) C:/denoise\lake.las: **Found invalid value of '0' for point's return number.**
(pdal pipeline readers.las Warning) C:/denoise\lake.las: Found invalid value of '0' for point's number of returns.

How to resolve this issues ,  Your effort will be appreciated. Thanks in advance

**Comment by abellgithub** [comment]
It's just a warning about your data. The reader is detecting the value '0'
for the return number field, which is invalid according to the
specification.

On Jul 27, 2017 2:46 AM, "ahmadshabbir99" <notifications@github.com> wrote:

I am trying to read and write LAS (*.las) file using PDAL but getting the
following warning messages and the reading and writing is not being done
correctly by PDAL reader and writer for las files.

(pdal pipeline readers.las Warning) C:/denoise\lake.las: *Found invalid
value of '0' for point's return number.*
(pdal pipeline readers.las Warning) C:/denoise\lake.las: Found invalid
value of '0' for point's number of returns.

How to resolve this issues , Your effort will be appreciated. Thanks in
advance

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PDAL/PDAL/issues/1629>, or mute the thread

**Comment by hobu** [comment]
This was answered on https://gis.stackexchange.com/questions/250008/pdal-reader-las-and-writer-las-error and GitHub tickets are not the proper question for user support questions. Please ask your question on the [PDAL mailing list](https://www.pdal.io/community.html#mailing-list)
