### ISSUE TITLE
JSON metadata dump invalid for LAS VLRs

### ISSUE THREAD

**Issue by huntm** [PDAL/PDAL#1648]
If I run `pdal info --metadata input.las` on a LAS file with VLRs, the resulting JSON defines `vlr_0` (and vlr_1, etc.) twice:

```
		"vlr_0": "AQABAAAACAAABAAAAQABAAEEAAABAAIAAAwAAAEAfn8DEAAAAQApIwQMAAABACkjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
		"vlr_0": {
			"description": "",
			"record_id": 34735,
			"user_id": "LASF_Projection"
		},
```

The impact is that with the JSON parser I'm using, the base64 data is lost and only the description/record_id/user_id object is retained.

[JSONLint](https://jsonlint.com/) confirms this is an error:
```
SyntaxError: Duplicate key 'vlr_0' on line 49
```

Perhaps something like this would work:
```
		"vlr_0": {
			"value": "AQABAAAACAAABAAAAQABAAEEAAABAAIAAAwAAAEAfn8DEAAAAQApIwQMAAABACkjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",

			"description": "",
			"record_id": 34735,
			"user_id": "LASF_Projection"
		},
```

**Comment by abellgithub** [comment]
This behavior is historic.  We used to produce XML output instead of JSON, and this is a direct translation of the XML nodes that we were creating.

This JSON we produce isn't invalid.  The issue is that the parser you're using doesn't know how to deal with duplicate keys.  I believe a newer standard suggests that you don't have duplicates, but it's hard to put such a cat back in the bag:

https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object

That said, your suggestion is a good one and it's trivial to change.  The only issue is that some may be depending on the old behavior.  Perhaps others will weigh in on making this change.

**Comment by abellgithub** [comment]
@msmitherdc: Thoughts?

**Comment by msmitherdc** [comment]
@abellgithub i don't think that this would impact us having this change made, Its possible that we are even parsing it wrong now and not catching it. I'll look into our code and see if this is affecting us now but i think its a good idea to make it correct and if that forces us to change something thats fine

**Comment by hobu** [comment]
I think the node with the base64'd data should just be inside the `vlr_0` node as a `data` member.

**Comment by msmitherdc** [comment]
concur, as it stands now, we are not getting the base64 value as we are just getting the last vlr key without the data

**Comment by msmitherdc** [comment]
@abellgithub can you add this to the 1.5-maintenance branch also?

**Comment by huntm** [comment]
Using this functionality now with no problems. Thanks!
