### ISSUE TITLE
writers.pgpointcloud only makes point patch ?

### ISSUE THREAD

**Issue by nimam90** [PDAL/PDAL#1663]
Hi everyone , 

i am new in pdal for my master thesis. it is very amazing. i want to read a point cloud as a ply file and write it into a postgresql database. but it seems that pdal only stores all of points as a one patch. how can i store them all separate as points ?

regards

**Comment by abellgithub** [comment]
We don't support this.  It's pretty unusual to want to access points one at a time.  Typically, the points are tiled and each tile is written as a patch.  However, pgpointcloud does support writing points (instead of a patch) directly to a table.  You'd have to modify PgWriter.cpp in order to get this functionality.
