### ISSUE TITLE
Unable to convert scaled value (inf) to int32 for dimension 'Z' 

### ISSUE THREAD

**Issue by shandoosheri** [PDAL/PDAL#1746]
i am trying to use the mongus filter using the pipeline example but i get the following error:

"PDAL: writers.las: Unable to convert scaled value (inf) to int32 for dimension 'Z' when writing LAS/LAZ file grid_close.laz"

any idea on what could be the issue

**Comment by chambbj** [comment]
My guess would be that you have ended up with an empty raster cell, possibly due to the orientation of your data set or choice of cell size. If you can share data and your pipeline, I could confirm. A basic word of warning though with the mongus filter...we know that our implementation is not 100%, so proceed at your own risk! Patches are always welcome.

**Comment by shandoosheri** [comment]
my goal is to implement the new method of filtering ground points from his paper titled "Ground and building extraction from LiDAR data based on differential morphological profiles and locally fitted surfaces." but i am just getting started.  i am currently using this pipeline
`{
  "pipeline":[
    "site.las",
    {
      "type":"filters.mongus",
      "extract":false,
        "cell":0.2
    },
    "site_ground.laz"
  ]
}`
and trying it on this file
[site.zip](https://github.com/PDAL/PDAL/files/1572984/site.zip)

**Comment by ahalota** [comment]
What would be the best way to handle an empty output?
