### ISSUE TITLE
PDAL runs out of memory with big .asc files

### ISSUE THREAD

**Issue by gabri94** [PDAL/PDAL#1818]
I'm trying to load a 6GB .asc files containing lidar relevations. However, after some time pdal gets kiled by the OS.  My PC has 16GB of memory + 16GB of swap. 

I saw that in previous version of pdal there was a cache filter, where is it gone?

**Comment by abellgithub** [comment]
Without know more about what you're trying to do we can't help you.  Perhaps you could post a pipeline or command.

**Comment by gabri94** [comment]
I'm trying to load a lidar file in .asc formato into a pgpointcloud database.
This is my pipeline:
```
{
	"pipeline":[
		{
			"type" : "readers.gdal",
			"filename" : "/opt/lidar/firenze_all"
		},
		{
			"type":"filters.reprojection",
			"in_srs":"EPSG:3003",
			"out_srs":"EPSG:4326"
		},
		{
			"type" : "filters.ferry",
			"dimensions": "band-1=Z"
		},
		{
      			"type":"filters.chipper",
			"capacity":"600"
		},
		{
			"type": "writers.pgpointcloud",
			"connection":"host='localhost' dbname='postgres' port='32768' user='postgres' password='secret'",
			"table" : "patches",
			"column": "pa",
			"srid": "4326",
			"output_dims": "X,Y,Z"
		}
	]
}
```

**Comment by abellgithub** [comment]
The chipper filter requires all points in memory to properly operate, so this pipeline won't work with streaming mode.  I don't have much to recommend at this point other than to increase the swap on your system or find a system with adequate memory.  If your input data has more than one band, perhaps you could use GDAL utils to filter down to one band in order to reduce the amount of data that's being loaded.

**Comment by gabri94** [comment]
Can you give me an estimate of adequate memory? Right now it's eating 32GB of ram for a file that's 6GB. How much would be adequate?
Is there any alternative to the chipper filter? I understood that it's almost mandatory with pgpointcloud.
Thanks
