### ISSUE TITLE
PDAL python package can not be imported

### ISSUE THREAD

**Issue by pglira** [PDAL/PDAL#1933]
I installed PDAL with OSGeo4W and everything works fine on the command line. Then I installed successfully the PDAL python package with `pip install pdal` in my conda environment. However, if I try to import the PDAL package in python this leads to:
```
>>> import pdal
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\miniconda3\envs\myenv\lib\site-packages\pdal\__init__.py", line 3, in <module>
    from .pipeline import Pipeline
  File "c:\miniconda3\envs\myenv\lib\site-packages\pdal\pipeline.py", line 2, in <module>
    from pdal import libpdalpython
ImportError: DLL load failed: The specified procedure could not be found.
```
Does anybody have an idea what's the problem?

**Update:**
I realized that running `import pdal` with `c:\OSGeo4W64\bin` as current directory works. However, if I add `c:\OSGeo4W64\bin` to my %PATH% still the DLL cannot be found.

**Comment by hobu** [comment]
Some other DLLs might not be found, or the libpdalpython.so itself is not being found due to pip, presumably. If you can run in a cmd.exe or shell that doesn't swallow the DLL window pop-up, maybe this will tell you what it thinks it is missing.

**Comment by hobu** [comment]
Please reopen when you have more information.

**Comment by chambbj** [comment]
@pglira I'm not sure what other OSGeo4W tools you may use, or how well these may play together, but you can now Conda install both PDAL and the PDAL Python Extension. Both are in the conda-forge channel under `pdal` and `python-pdal` respectively.

**Comment by Hutch07** [comment]
I also had the same issue and it was fixed by using pdal in a conda environment.

**Comment by jdafermos** [comment]
Hi, i have also installed PDAL using OSGeo4W (64-bit) and installed the python package with "pip install pdal" inside the virtual environment of my Django application in Visual Studio 2017. So, when issuing "import pdal" in the VS Python Interactive Window all goes well. But when doing the same inside my "views.py" script it raises the same error @pglira is describing (ImportError: DLL load failed: The specified procedure could not be found.).

I used Dependency Walker on "libpdalpython.cp36-win_amd64.pyd" and it showed me that about 800(!) dependencies are missing. Files such as "api-ms-win-crt" or "api-ms-win-core" among many others, which are part of MS-VC Redistributables - if i've correctly understood.

I tried to install VCRedist 2015, but setup fails when 2017 are already present. After all it seems that the 2017 version of them effectively replaces the 2015 one. I also attempted downloading the missing dlls separately, but it is quite frustrating due to their huge number and from what I've read Microsoft does not recommend doing this at all, so I quit that.

Does anyone know anything about fixing this?

**Comment by hobu** [comment]
> inside the virtual environment of my Django application in Visual Studio 2017.

PDAL in OSGeo4W is built on 2015, and to get to 2017, I think you're going to have to build the entire stack yourself.

**Comment by jdafermos** [comment]
@hobu Thank you so much for the reply, I will try to do that.

**Comment by forkozi** [comment]
@jdafermos, I'm having a similar issue with not being able to import pdal from within a script while working in Visual Studio 2017.  Have you made any progress with this.  I can import pdal from a regular conda python command line, but not from within VS :(

**Comment by Hutch07** [comment]
No.  I got out of PDAL and went to whitebox tools.

**Comment by jdafermos** [comment]
@forkozi Hi, yes before trying to build PDAL myself, I simply stopped writing my code inside VS and switched to command-line django (1.11.x in virtual environment) using Notepad++ instead and it worked! That was on my PC.

However, when I tried to install the same things on my laptop, it wouldn't "pip install pdal" at all. After some searching, I installed VS Build Tools (with VS 2017 already installed) and after that "pip install" was successful but "import pdal" within views.py would fail again (this time not from within VS).

So I moved things to a third PC, to which I installed VS 2017 (Universal Win. Platform dev. + Python dev.), VS Build Tools (VC++ Build tools, tools for CMake, testing core features), SDK 10, Django 2.x (in virtual environment). Please note that in all cases i've been using 64-bit versions. Again, it wouldn't pip install, producing «error: command 'cl.exe' failed: No such file or directory». After some more searching, I opened «x64Native Tools Command Prompt for VS 2017» from Start Menu\VS Tools and: in its command line I activated my virt. env. and then issued "pip install pdal" and it worked. Since then "import pdal" has been working without problems from my views.py and my app has been working.

I still haven't determined whether you need both VS and VS Build Tools installed. Or whether you need all those components of VS I mentioned above. If you can find out anything about that, please tell.

I haven't successfully installed PDAL to work with Django 2.x on my first PC, although it is working with Django 1.11.x, but I hope I will. I'm thinking of simply copying PDAL files and folders from the "site packages" folder of the working PC's virtual environment to the other one and see if it works.

**Comment by hobu** [comment]
PDAL's python needs to build against the PDAL library to work, which is why your pip install is not working without the native tools activated. 

I would caution against mixing 2017 and 2015 runtime stuff though.

Also, don't run PDAL operations in Django 😃 It's highly likely things leak. I've never done any of the Python stuff in long running process scenarios. There's more work to be done on this topic.

**Comment by jdafermos** [comment]
Well I hope it keeps running in django as it is, because it's for my thesis application and i'm running out of time! I can't abandon django anymore, it has to work! :-)

**Comment by vonnonn** [comment]
When importing pdal from vs code I get a [WinError 2] The system cannot find the file specified but it loads fine from Jupyter Lab in the same environment. Also, I can import all the other packages fine in vs code. I used the "conda install -c conda-forge python-pdal" method. Any thoughts? 

The bottom error points to line 1435  hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

**Comment by hobu** [comment]
This works just fine for me with a new environment, and when I activate that environment in Code.

![Screenshot 2022-02-21 182223](https://user-images.githubusercontent.com/87751/155042003-020b3a4c-3120-4051-82b4-15d3e43cb53e.png)

![Screenshot 2022-02-21 182418](https://user-images.githubusercontent.com/87751/155041979-3f8070b0-9ffb-4a67-8b07-30b9d006c133.png)

**Comment by vonnonn** [comment]
Strange. I wonder if it has something to do with not having admin rights. I had no problem running pdal on vscode at home on my own desktop.

**Comment by hobu** [comment]
Try running in a cmd.exe to see if the GUI will pop the error window stating which DLL(s) it can't find.

**Comment by vonnonn** [comment]
Is that different from the python command prompt screenshot above?

**Comment by vonnonn** [comment]
![image](https://user-images.githubusercontent.com/68934869/156045000-71fb7ab0-f121-47d3-82db-78bb90b4f155.png)

**Comment by hobu** [comment]
The PDAL Python bindings expect to run the `pdal` command to learn the options and drivers that are available. Is this not installed into your environment? What happens when you try to issue the `pdal` command?

**Comment by vonnonn** [comment]
Yes, it's in the environment. It runs fine from the python cmd prompt. It also runs fine form jupyter notebook. It's just vscode.
![image](https://user-images.githubusercontent.com/68934869/156230156-5bac9946-6234-4353-bedf-79c6ea20b955.png)
![image](https://user-images.githubusercontent.com/68934869/156230338-70b5a5e8-739d-4e22-9470-b44940be82b7.png)

**Comment by hobu** [comment]
Do you have your conda environment activated in your vscode project? The GUI is quite confusing there. If it works in a conda prompt, it shouldn't be any different in vscode.

**Comment by vonnonn** [comment]
Good grief! That was it. Thanks Howard. I was under the impression that vscode activated the env when I selected the kernel because other packages could be imported. This time I activated the env from the conda prompt than typed "code" from there and it imported pdal.
Cheers!

**Comment by najacks** [comment]
I'm having the same problem (unable to import pdal in vscode although it works in a conda shell). My conda environment with pdal is activated in vscode.
![image](https://user-images.githubusercontent.com/82046162/169152532-f1e03f31-39d9-4a00-a58b-646942d2e605.png)
![image](https://user-images.githubusercontent.com/82046162/169152613-7582ec7b-0cec-4a64-a75f-12ecb96c6d56.png)

**Comment by najacks** [comment]
Update:

The problem was that the **terminal** in vscode wasn't using the python interpreter as the active environment (I guess the same problem as vonnonn above, but launching from the conda prompt wasn't working for me, because VS Code would still change the terminal that was running the program to the PowerShell default, that wasn't recognizing conda and not activating the environment, even though the python path was set to the correct environment )

Sort of a workaround solution (I think it's possible to get PowerShell to recognize conda, but I didn't bother trying to figure that out): I changed my default terminal in VS Code to Command Prompt (cmd.exe), and added these lines to my VS Code settings to make sure the environment is always activated when I'm running my scripts. (What's the difference between these two settings? Good question; it's just working now so I'm going to leave it at that...)

In VS Code settings.json:

    "terminal.integrated.defaultProfile.windows": "Command Prompt",
    "python.terminal.activateEnvInCurrentTerminal": true,
    "python.terminal.activateEnvironment": true,


based on info found here:
https://stackoverflow.com/questions/54828713/working-with-anaconda-in-visual-studio-code
and here:
https://stackoverflow.com/questions/44597662/conda-command-is-not-recognized-on-windows-10
