### ISSUE TITLE
Delaunay should be promoted from plugin status to one of our core stages

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#1969]
It requires no additional third-party dependencies.

@plimkilde Thoughts? I assume it started this way because you were finding your geometry package separately and later decided to just embed it.

**Comment by abellgithub** [comment]
What's the advantage?  It's more to dynamic link at start time.

**Comment by hobu** [comment]
There is no reason for this to be a plug-in if AppVeyor and Travis are passing.

**Comment by abellgithub** [comment]
This needs tests.  There are none.

**Comment by hobu** [comment]
> On Apr 25, 2018, at 12:59 PM, Andrew Bell <notifications@github.com> wrote:
> 
> This needs tests. There are none.

Something that creates a simple Hull from one of the existing test files in the test suite would be sufficient.

**Comment by chambbj** [comment]
@plimkilde I am seeing now (in #1985) that the Delaunay_psm may not be all that portable. Were there drawbacks to just compiling the whole Geogram library? They at least seem to claim support for the major platforms.

**Comment by plimkilde** [comment]
@chambbj To be honest, I hadn't tried compiling the whole Geogram library when implementing the filter, as it seemed the PSM fit the task neatly (as described at http://alice.loria.fr/software/geogram/doc/html/geogram_PSM.html). I just tried building from source as well as installing the pre-built RPM, both of which failed (but that may be saying more about the ancient RHEL/CMake version I am stuck with than the library).

I don't see any reason why the PSM should be less portable than the full library, and since Geogram did not seem to be included in mainstream package databases, a copy-paste inclusion of the PSM seemed the simplest approach to me.

**Comment by hobu** [comment]
Is this done and closeable now?

**Comment by abellgithub** [comment]
I think there were a bunch of issues as noted above.  I think there's a bunch of work to be done to do this properly.

**Comment by hobu** [comment]
This isn't happening for 1.8
