### ISSUE TITLE
Kernel Plugins Don't Load

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#1971]

**Comment by jw3** [comment]
I also noticed failures around kernel loading, however thought that it was related to my plugins needing updated for 1.7.  Just back to the point of loading up a custom kernel driver today.

The kernel is detected and listed in available commands, but get this when trying to use it

```
(PDAL Error) Command 'mykernel' not recognized
```

**Comment by jw3** [comment]
Building the kernel in to pdal as a static plugin as a workaround.

**Comment by jw3** [comment]
Do kernels plugins abide by the same naming conventions as stage plugins?

**Comment by jw3** [comment]
... Looks like perhaps but the command is tolowered later. https://github.com/PDAL/PDAL/blob/938faa39053128450d1ba1be306a9dd5edfb3712/apps/pdal.cpp#L343

We can make that work, its just the one kernel.

**Comment by jw3** [comment]
>  It was actually lower case previously and was changed to match the other plugins while converting.

For posterity; The difference was that previously our kernel cmake targets had uppercase, to match the our other plugins, while the filter name that got registered with pdal was lowercase (because it had to work like that due to the source quoted above).  Now in 1.7 it looks like a plugin name must match the library name.  Dropping the case of our kernel for the library targets works.
