### ISSUE TITLE
Relocate plugins so that they can be built independently from PDAL

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#2005]
# Current Situation

We currently offer PDAL binaries on various platforms. For many users, the binaries are sufficient. Some users still need to build PDAL from source. Not counting core developers who routinely build PDAL from source, these users probably fall into two categories.

1. Developers who are linking against PDAL and for whom the binary distribution is insufficient. Maybe they need to build in debug mode for example.
2. Users/developers who need one of the optional PDAL plugins that was not provided in the binary distribution.

In the second scenario, we are doing a disservice to force them to rebuild the entire library, when it would suffice to build the plugin alone.

# Recommendations

1) We should refactor the PDAL repository to **only** build core stages. That doesn't mean gutting the plugin framework, rather making a clear distinction between core (lives in the source tree, is built and tested 100% of the time, always part of the distribution) and plugin (external to source tree, built, tested, and distributed separately from PDAL). For the most part, this would consist of relocating the current plugins to alternate repositories. Does this mean that we follow the lead of `PDAL/prc`, `PDAL/python`, `PDAL/java` and the likes? That could get noisy with nearly 20 plugins. A single, `PDAL/plugins` repository with `BUILD_XXX` options could be cleaner.

2) We have already discussed converting Hexbin from a plugin to a core component of PDAL. Nearly every distribution of PDAL also builds Greyhound, Icebridge, NITF, pgpointcloud, and SQLite plugins. We should consider also making these part of the core PDAL offering, simplifying the configuration of PDAL so that there is less variability in how it is built and subsequently distributed.

**Comment by hobu** [comment]
The determination of what is a core plugin or what is not is driven by its needed support libraries. If there's an external library needed and we can't directly embed it, it's a plugin. If we could embed the library, but the license is not compatible, like [PRC](https://github.com/PDAL/PRC), it's a plugin. I just removed this restriction for hexer #2001 by relicensing the underlying library to BSD and embedding it in PDAL like we do for other things 

> For the most part, this would consist of relocating the current plugins to alternate repositories. 

I dislike this proposal because spreading plugins around like this would have some painful consequences:

* `git submodule` is terrible
* We would need to invest in versioning and hardening of plugins to ensure they work independently of PDAL version
* library convenience for someone building from source would go way down, and I think it would increase the support load of "why doesn't such and such plugin load?" more than is happening already.
* Does each plugin now get its own release cycle? That's a big administrative load.

> Nearly every distribution of PDAL also builds Greyhound, Icebridge, NITF, pgpointcloud, and SQLite plugins. 

All of these require external libraries that are too big for us to embed/fork into PDAL. I'm not sure how we make them part of core PDAL without making all of their support libraries also be required. We already get complains about our required library list being too long (and it's basically just GDAL at this point). The fury would get worse to add hard requirements for these.

**Comment by chambbj** [comment]
> If there's an external library needed and we can't directly embed it, it's a plugin.

I've never thought about it this way. I've always thought of a plugin as something that was 1) externally developed and cared for (perhaps due to licensing, but not by definition), or 2) carried a dependency that was uncommon or cumbersome enough that we didn't want to make it a required dependency.

> We would need to invest in versioning and hardening of plugins to ensure they work independently of PDAL version.

For the sake of our potential plugin writers, we should probably do this anyway. Or let go of the plugin concept and maybe call this something else altogether.

> library convenience for someone building from source would go way down, and I think it would increase the support load of "why doesn't such and such plugin load?" more than is happening already.

How so? I feel this proposal leads toward a one right way to build PDAL, rather than having so many switches that may or may not have been turned on during compilation.

> Does each plugin now get its own release cycle? That's a big administrative load.

I suppose. I could see this going one of two ways. First, individual plugins. That's a lot of repos and a lot of releases to manage. Second, a single plugins repo. That's just one additional release. The advantage of separate repos is that you could better identify who is going to be the maintainer of a particular plugin.

> I'm not sure how we make them part of core PDAL without making all of their support libraries also be required.

I am going with the assumption that we would just make them required. If that's not palatable, then I agree that this aspect of the proposal is a non-starter. I see no need to embed the libraries.

**Comment by hobu** [comment]
> Second, a single plugins repo. That's just one additional release. The advantage of separate repos is that you could better identify who is going to be the maintainer of a particular plugin.

But that's just going to be us anyway, right? Less repos and less releases means our screwups are contained to fewer places 😄 

> I am going with the assumption that we would just make them required. If that's not palatable, then I agree that this aspect of the proposal is a non-starter. 

I think this is unpalatable for NITF/Nitro, HDF, SQLite, and psql dependencies. There's not even support for them on all of the platforms and they have version sensitivities. I could see curl being required as reasonable, but it opens up security sensitivities for some organizations. We see that with GDAL too.

**Comment by chambbj** [comment]
Alright. It was worth a try :wink:
