### ISSUE TITLE
Problem at Mongus filtering

### ISSUE THREAD

**Issue by muzo583** [PDAL/PDAL#2041]
Hi all, I get this error, any idea?

$ pdal pipeline filter_ground.json

filter_ground.json file include:
{
  "pipeline":
[
    "Turmak_100m_1.las",
    {"type":"filters.splitter",
     "length":"20"
    },
    {
      "type":"filters.mongus",
      "extract":false
    },
    {
      "type":"writers.las",
      "filename":"Turmak_100m_1_ground.laz",
      "forward":"all"
    }
]
}

`Level 7
median troubleshooting
1	1
1
1.63042e-322	0
0, 
median troubleshooting
1	1
1
1.63042e-322	0
0, 
Level 6
median troubleshooting
1	1
1
1.63042e-322	0
median troubleshooting
1	1
1
1.63042e-322	0
Level 5
median troubleshooting
1	1
1
1.63042e-322	0
median troubleshooting
1	1
1
1.63042e-322	0
Level 4
median troubleshooting
4	4
0
0.0193843	0.0603543
pdal: /home/dell/opt/source/pdal-trunk/vendor/eigen/Eigen/src/Core/PlainObjectBase.h:374: void Eigen::PlainObjectBase<Derived>::resizeLike(const Eigen::EigenBase<OtherDerived>&) [with OtherDerived = Eigen::CwiseUnaryOp<Eigen::internal::scalar_abs_op<double>, const Eigen::CwiseBinaryOp<Eigen::internal::scalar_difference_op<double, double>, const Eigen::ArrayWrapper<Eigen::Matrix<double, -1, -1> >, const Eigen::CwiseNullaryOp<Eigen::internal::scalar_constant_op<double>, const Eigen::Array<double, -1, -1> > > >; Derived = Eigen::Array<double, -1, 1>]: Assertion `other.rows() == 1 || other.cols() == 1' failed.
Aborted (core dumped)
`

Thanks in advance.

**Comment by chambbj** [comment]
A few thoughts for you.

1. We might get a little more information about what is going on by running again with `--verbose 5`.
2. Unless you are really interested in Mongus specifically, you could also try PMF and SMRF which are more tried and true ground segmentation filters.
3. Because you are using the splitter first to create 20 m tiles, the max level option `l` in Mongus probably needs to be reduced. It defaults to 8 levels, meaning that with the default cell size of 1 m, your cell size in the first stage of processing is 256 m, much larger than the data you are passing into the filter stage. Try a max level of 5, which results in an initial cell size of 32 m (the Mongus method does suggest that the max level be set such that the _first_ iteration operates on a single tile spanning the entire dataset, but after that it should operate on progressively smaller tiles, all automatically calculated by the algorithm).

**Comment by muzo583** [comment]
@chambbj 
Thank you very much. I will use other ground filtering functions.
