### ISSUE TITLE
LAS point clouds to PostgreSQL-POSTGIS with PDAL

### ISSUE THREAD

**Issue by CBalmus** [PDAL/PDAL#2218]
Dear all,

I am not sure whether this is the right place for my questions, but I am trying my luck :) .

I am currently experimenting with a batch import of a series of .las point clouds (around 22.300 files with an estimated total of 10.000.000.000 Points) into a PostgreSQL with POSTGIS database by means of PDAL. The workflow I developed looks as follows:

1. In the OSGeo4W Shell I am generating a .sqlite tile index to index my .las files.

2. I then write a JSON Pipeline where I am using the "readers.tindex" reader from PDAL to read the created index, then the "chipper filter" to group the points into patches and in the end a "pgpointcloud writer" to write the points as patches directly into the database. I run the pipeline in the OSGeo4W Shell.

While my workflow works, I have come to the following conclusions:
1. although I am using the chipper filter to group the points from the point cloud into patches, which I would have expected reduces significantly the size of the database table (TOAST Table), I have noticed that it will only be reduced to 75% of the original data and that irrespective of the size of the patch. 
I am somehow surprised because when trying with .laz files there will be a linear decrease, meaning the more points one groups per patch, the smaller will the database table size be. I was expecting the same behaviour with .las files.

Question: Is there something else that can be done to reduce the size of the database table? I can imagine that converting first the .las files to .laz would do this, but I was wondering if there is not something database-related that could do the trick for the .las data without having to convert.

2.  Second of all, the time needed to write the data into the database is also very long (it is true, there are a lot of points). 

Question: Is there something that can be done to improve the loading time to the database?

Many thanks in advance,

**Comment by hobu** [comment]
I would first question your assumptions of why you want to write point cloud data into PostgreSQL in the first place. When we developed the Oracle Point Cloud and pgpointcloud tools we had notions of storing lots of point clouds in transactional databases and in the process, we learned a number things:

1) We never transacted the points. No matter how we arranged them in the database, we never had the need for the performance cost of a transactional engine over the data. 

2) While it was convenient to be able to interact with the points in SQL, because the volumes of data were typically so large, it took forever and parallelization of the task required bespoke database tools. This may be improved now that PG has really been aggressive with their parallelization efforts.

3) Processing time was dominated by getting data in and out of the database, and all of our I/O ended up having to go through the choke point of the database. Getting parallel i/o was ether very expensive or very complex.

Given this experience, we developed [Entwine](https://entwine.io), which allows you to organize very large collections of data as an octree, parallelize the process using whichever cloud or container tools you wish, and supports storing data in [LASzip](https://laszip.org) as well as uncompressed binary encoding. It too is open source, and with it, we can store the 640 billion points that represent Netherlands AHN2 as a single resource in S3 – allowing any client application to make requests in a TMS-like fashion across the data at any depth in the tree they wish. This allows thin browser-based clients such as [Potree](http://potree.org) or PDAL itself (upcoming [readers.ept](https://github.com/PDAL/PDAL/blob/master/doc/stages/readers.ept.rst) in PDAL 1.8) to control how they fetch data. See it in your browser at http://potree.entwine.io/data/ahn.html

Sorry for the sales pitch 😄, but this is the long way of saying, that you'll have to invest yourself in improving the software if you need better point cloud database performance. We have moved on to a different approach that better fits our use scenarios.

![ahn](https://user-images.githubusercontent.com/87751/46611522-ab8f3700-cad3-11e8-8429-0d6aecce1a98.jpg)

**Comment by CBalmus** [comment]
Dear Sir,

First of all, many thanks for your quick reply. 

Now the reasoning behind our trials is twofold. On the one hand we want to put to our clients' disposal the various point cloud data that we have for our region (either derived from airborne laserscanning or from street driving - Cyclomedia) via personalized ready-to-use tools. On the other hand we would like to find a way to better manage our big data. 

Unfortunately, any open source or web-storing solutions are currently excluded in our case since we deal with sensitive data that should only be made available to specific categories of users. That is why we thought of the database way which is already implemented in our workflows for various geodata. 
The question would then be: can Entwine interact with a database when it comes to reading/writing of data?

As far as the client is concerned, we are currently thinking of potential options, but are not there yet.

**Comment by hobu** [comment]
> Unfortunately, any web-storing solutions are currently excluded in our case since we deal with sensitive data that should only be made available to specific categories of users. That is why we thought of the database way which is already implemented in our workflows for various geodata.
The question would then be: can Entwine interact with a database when it comes to reading/writing of data?

* Entwine is not required to use S3. Any local file system or HTTP'able server is sufficient as well. 
* Entwine does not interact with databases.

**Comment by Jean-Roc** [comment]
Hi @hobu, could you write something about the actual state and usecases of pdal, greyhound and entwine ? The ongoing work on the latter makes me ponder about greyhound's use in the chaintool. Thank you in advance :)

**Comment by tomvantilburg** [comment]
From the perspective of a user who handles most of his data from within postgres: I find it very convenient indeed to access my points from within a query, especially because my data never travels outside the database, apart from aggregated versions. It is currently even worth the pain of waiting for TB of data to load into pgpointcloud tables and investing in expensive SSD's.

However. 
As @hobu points out, transaction support is never needed. In fact, the only thing I really need is a way to get my points into dbase memory asap, based on a spatial index, so I can do my postgis foo on it. Therefore it would be enough to be able to reach those points from the database in a convenient way like a foreign-data-wrapper. If only I could index for instance the EPT files in the database based on bbox and tree-level, I would only have to open the files and pull in the points at query time. Roughly in a similar way as the OGR FDW works: https://github.com/pramsey/pgsql-ogr-fdw)
Would that makes sense?

(just dropping this post here so any able C-developer might get inspired ;-) )

**Comment by connormanning** [comment]
@tomvantilburg: PDAL has recently added some native tools for a similar workflow with the combination of the [EPT reader](https://github.com/PDAL/PDAL/blob/master/doc/stages/readers.ept.rst) (which provides spatially-accelerated access to EPT data) and the [Mongo filter](https://github.com/PDAL/PDAL/blob/master/doc/stages/filters.mongoexpression.rst) (which provides arbitrary filtering logic).

Of course this is more limited and won't allow you to 'do your postgis foo on it', but can provide at least a small bit of similar functionality without a database.

For example, downloading the Statue of Liberty, without noise points, from a ~5 billion point dataset (full data [here](http://potree.entwine.io/data/nyc.html)) in ~2 seconds:
```
[
  {
    "type": "readers.ept",
    "filename": "http://na-c.entwine.io/nyc",
    "bounds": "([-8242669, -8242529], [4966549, 4966674])"
  },
  {
    "type": "filters.mongo",
    "expression": { "Classification": { "$ne": 7 } }
  },
  "statue-of-liberty.las"
]
```

The latter half of your post does make sense and is certainly possible - we've discussed that exact workflow a few times while designing EPT.  We'll see if inspiration strikes...

**Comment by tomvantilburg** [comment]
For the archive:

I wrote a small wrapper around pdal-python for postgres that enables you to draw points from ept from a postgres query. Be aware that arbiter needs to be able to find a home directory in the environment vars which can be set in a special postgres config file called 'environment'.


```
CREATE TYPE ahnpoint AS (
  X float, 
  Y float,
  Z float, 
  Intensity SmallInt, 
  ReturnNumber SmallInt, 
  NumberOfReturns SmallInt, 
  Classification SmallInt, 
  UserData SmallInt, 
  PointSourceId Integer, 
  NormalX float,
  NormalY float, 
  NormalZ float, 
  Curvature float, 
  Coplanar float
);

DROP FUNCTION IF EXISTS ept_reader(text,text);

CREATE OR REPLACE FUNCTION ept_reader(polygonwkt text,eptdir text default '/var/data/entwine/amsterdam/ept.json')
  RETURNS SETOF ahnpoint
AS $$
"""
Parameters
----------
filename : pathname
    Path to ept directory
polygon_wkt : wkt
    WKT with clipping polygon

Returns
-------
points : setof ahnpoints
    The ept points
"""

import traceback
import time
import numpy as np
import pdal
from shapely.wkt import dumps, loads

try:
  p = loads(polygonwkt)
  bbox = p.bounds

  bounds = "([{},{}],[{},{}])".format(bbox[0], bbox[2], bbox[1], bbox[3])
  json = """
  {
    "pipeline":[{   
        "type": "readers.ept",
        "filename": "%s",
        "bounds": "%s"
      },{
        "type": "filters.range",
        "limits": "Classification[6:6],NumberOfReturns[1:1]"
      },{
          "type":"filters.crop",
          "polygon": "%s"
      },{
        "type": "filters.sample",
        "radius": 0.25
      },{
        "type": "filters.normal",
        "knn": 8
      },{
        "type": "filters.approximatecoplanar",
        "knn": 8,
        "thresh1": 25,
        "thresh2": 6
      }

    ]
  }""" % (eptdir,bounds,polygonwkt)

  pipeline = pdal.Pipeline(json)
  pipeline.validate() # check if our JSON and options were good
  count = pipeline.execute()
  arrays = pipeline.arrays
  return arrays[0]
except:
    var = traceback.format_exc()
    plpy.warning("Unexpected error:", var)
    return []

$$ LANGUAGE plpython3u;

SELECT * FROM ept_reader('POLYGON((122495.07 489425.596,122489.575 489428.012,122487.57 489423.454,122489.52 489422.596,122493.064 489421.037,122495.07 489425.596))');
```
