### ISSUE TITLE
hub.docker.io: PDAL/PDAL:latest should be PDAL/PDAL:1.7.2

### ISSUE THREAD

**Issue by frgomes** [PDAL/PDAL#2241]
It's a good practice to assign explicit tags to images, since _latest_ is not a stable tag.
This expedient avoids accidental upgrade (and, in general: unwanted upgrades!) on container platforms when _latest_ moves to a new image.

**Comment by hobu** [comment]
We have thought of `pdal/pdal:latest` as "latest release", and it is built of of the `1.7-maintenance` branch every time there is a commit to that branch.

`pdal/pdal:1.6` tracks the `1.6-maintenance` 

When 1.8 is released, `pdal/pdal:1.7` will track `1.7-maintenance`

**Comment by connormanning** [comment]
I'm not sure I understand how this alleviates the issue you're describing, because once 1.8 is released (for example) you'll run into the same issue unless you're on a numbered release tag.  Maybe I'm misunderstanding you, but in my mind if you're using `latest` it's very clear that you're not using a stable tag.

**Comment by hobu** [comment]
`pdal/pdal:1.7.1` is available, but I see we hadn't made a `pdal/pdal:1.7.2`. As you can tell this process is entirely manual.

**Comment by frgomes** [comment]
It's OK to have _latest_ as an alias to some stable tag.

**Comment by connormanning** [comment]
I fully agree - that tag should exist and was accidentally not created on that release.  I was confused by the talk of `latest` since that tag will never be stable no matter what approach is used.
