### ISSUE TITLE
[Contributing Guidelines] Broken Link & No Formatter Specified

### ISSUE THREAD

**Issue by sunapi386** [PDAL/PDAL#2374]
On the [Contributing page](https://github.com/PDAL/PDAL/blob/master/CONTRIBUTING.md) the link to [PDAL's coding conventions](http://pdal.io/development/conventions.html) is `404`. 

I was looking for code style formatting guidelines, I'd like to `clang-format` the file I work on to match style consistency.

**Comment by sunapi386** [comment]
I missed this [conventions](https://pdal.io/project/conventions.html) document.

> We use astyle (http://astyle.sourceforge.net) as a tool to reformat C++ source code files in a consistent fashion. The file astylerc, at the top of the github repo, contains the default settings we use.

This was what I was looking for.

**Comment by hobu** [comment]
> This was what I was looking for.

We are not very strict with the styling, however. There is no auto-formatting on commit, for example, and we would be rather lax on the styling of an individual contribution if it were contained. If it was touching a lot of publicly visible stuff, please try to follow the styling as best you can. 

We don't have enough external contribution to reject Pull Requests because they don't match a styling guide 😉

**Comment by chambbj** [comment]
Also, don't know that we've ever pushed anything "official" but at least a
couple of us do use clang-format in a manner that mimics pretty closely the
astyle output. Just to say, it's possible.

**Comment by hobu** [comment]
> at least a couple of us do use clang-format in a manner that mimics pretty closely the astyle output

Maybe we should push them to the tree.

**Comment by chambbj** [comment]
Done. See https://github.com/PDAL/PDAL/blob/master/.clang-format. Not sure
how this compares to what @gadomski had been using.

**Comment by gadomski** [comment]
Mine didn't match particularly well; having a curated e.g. in the tree will be helpful, thanks @chambbj!
