### ISSUE TITLE
Writers.gdal off by half-pixel

### ISSUE THREAD

**Issue by klassenjs** [PDAL/PDAL#2412]
I noticed when round tripping a DEM through readers.gdal to LAS (or CSV) and then back to writers.gdal that the output was shifted from the input by about half a pixel.

I created a small 10x10 pixel test DEM and a simple pipelines to convert it to CSV via writers.text.  The X,Y coordinates in the CSV file match the center of the pixels of the source DEM as shown by QGIS, so I suspect that readers.gdal is correct.  I have another pipeline that is a readers.gdal into writers.gdal and QGIS shows the output DEM is shifted.

I have attempted at a patch to writers.gdal that appears to fix this shift.

https://github.com/klassenjs/PDAL/commit/c80963e938853ebd63aebe4e8a6ce7e1d5d53cbf

[test-case.zip](https://github.com/PDAL/PDAL/files/2984553/test-case.zip)

**Comment by klassenjs** [comment]
Note that in the test case I have radius=1.0.  This is so there is output in the broken state.  After the patch, the radius can be much smaller say 0.2 or 0.1 and still work.  The intent is that each output grid cells should all have exactly one point contributing to it.

**Comment by abellgithub** [comment]
The issue is that the input tiff is offset by 1/2:

```
$ gdalinfo dem_utm15.tif

...
Origin = (499999.500000000000000,5000000.500000000000000)
Pixel Size = (1.000000000000000,-1.000000000000000)
Metadata:
  AREA_OR_POINT=Area
  TIFFTAG_DOCUMENTNAME=eye.tif
  TIFFTAG_SOFTWARE=GraphicsMagick 1.4 snapshot-20181020 Q16 http://www.GraphicsMagick.org/
Image Structure Metadata:
  INTERLEAVE=BAND
Corner Coordinates:
Upper Left  (  499999.500, 5000000.500) ( 93d 0' 0.02"W, 45d 9'12.53"N)
Lower Left  (  499999.500, 4999990.500) ( 93d 0' 0.02"W, 45d 9'12.21"N)
Upper Right (  500009.500, 5000000.500) ( 92d59'59.56"W, 45d 9'12.53"N)
Lower Right (  500009.500, 4999990.500) ( 92d59'59.56"W, 45d 9'12.21"N)
Center      (  500004.500, 4999995.500) ( 92d59'59.79"W, 45d 9'12.37"N)
Band 1 Block=10x10 Type=UInt16, ColorInterp=Gray
```

When PDAL reads the file, it properly assumes that the CENTER of each pixel is offset by 1/2.  The output from reading the file into a text file is:

```
$ pdal translate dem_utm15.tif out.txt
$ head out.txt
"X","Y","band-1"
500000.000,5000000.000,1.000
500001.000,5000000.000,0.000
500002.000,5000000.000,0.000
500003.000,5000000.000,0.000
500004.000,5000000.000,0.000
500005.000,5000000.000,0.000
500006.000,5000000.000,0.000
500007.000,5000000.000,0.000
500008.000,5000000.000,0.000
500009.000,5000000.000,0.000
500000.000,4999999.000,0.000
500001.000,4999999.000,2.000
500002.000,4999999.000,0.000
500003.000,4999999.000,0.000
...
```

When the GDAL writer creates a raster from this data, it has no idea that you want your raster offset by 1/2.  It is calculating data for the cell center based on the input.  By default, each cell center is at a position (X + .5, Y + .5) where X and Y are integers (given an resolution of 1).  When imputing a value for each cell, the driver uses the radius to find nearby points.  In this case, the nearby points are found are in the corner of each cell, rather than the center.  This "shifts" the data from the original position to position PDAL believes is the cell center.  You can tell PDAL where to place the raster origin with the `bounds` option.  In your case, I think you want to add
```
"bounds": "([499999.5. 500009.5], [4999990.5, 5000000.5])"
```
to the writers.gdal options to match the input raster.

**Comment by klassenjs** [comment]
Setting the bounds as you suggested also works, although it feels a little clunkier.

What isn't intuitive to me is: why does PDAL want to align the output raster (particularly a raster where pixels are interpreted as area) so that the (boundary of the) points fall on the raster grid (between the pixels) rather than the pixel centers?

That then seems like it is currently making the raster too small. The raster can't really represent a point that falls on the edge of the raster.

(I'm trying to keep in mind how this applies for most point clouds that aren't a regular grid, but that isn't where my head is at today.)

**Comment by abellgithub** [comment]
I believe that the current choice of origin is based on the [points2grid](https://opentopography.org/otsoftware/points2grid) filter, which preceded writers.gdal.  We attempted to maintain behavior but improve the implementation.  You make a fair case for using a position offset from the point bounds for the origin.  As you say, most point cloud data sourced from a raster.  There are potential edge effects no matter what is done depending on the algorithm used to generate the raster, so the origin isn't usually critical.  We have no way of knowing what a user wants, which is why the `bounds` option exists.

There may be an OB1 error in the maximum of the `bounds` that might make my suggested bounds create a raster that is 1 too small in both directions.  Increasing the maxes a teeny bit should get around that.  I opened https://github.com/PDAL/PDAL/issues/2415 to address this.
