### ISSUE TITLE
writers.las fillForwardList() keeps appending to "all" forward list

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2452]
In LasWriter::fillFowardList(), the "all" vector is re-initialized each time the function is called, adding duplicates to the vector.  This doesn't hurt anything, but makes the list unnecessarily large.

**Comment by connormanning** [comment]
To add to this: because this is insertion is to the *front* of the vector, it's at least one full copy (or at worst, 3, not sure if the compiler is optimizing it into a single insert) of every entry in this ever-growing dataset for every LasWriter initialization throughout a process.  This has massive performance impacts for C++ API users that may be creating many LAS/LAZ files over time in a single process.

So while from a logical perspective it may not hurt anything (although as a side note, UB would occur if multiple LasWriters were initialized across multiple threads), from a performance standpoint this is an important fix.

**Comment by connormanning** [comment]
Fixed via #2451.
