### ISSUE TITLE
Remove stream option from pipeline kernel

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2639]

**Comment by hobu** [comment]
I can make the case for this feature. There are situations where you would want to force the invocation of a streamed pipeline (say you are in a low memory environment), and running `pdal pipeline --stream` over user-defined input that you don't control allows you to immediately reject pipelines that are not streamable with an error message rather than running until you run out of resources.

Let's keep it for now.

**Comment by abellgithub** [comment]
We don't currently support this as you're expecting it works.  We'd have to do something to make it happen.  The point of this issue is to remove an option that is a no-op.
