### ISSUE TITLE
Broken ubuntu build

### ISSUE THREAD

**Issue by nicolas-chaulet** [PDAL/PDAL#2648]
Hi,
It seems that commit 46ecc4d622c1757d8f4effd75519f36e55d56fdf breaks the ubuntu build. Maybe I am running with an older image but I am pretty sure you would have a similar problem. Reverting those lines fixes the issue.

**Comment by hobu** [comment]
sorry for the noise. I was just catching up to all of the docker failures this morning. For some reason GDAL_VERSION is not properly set on Ubuntu but it is on every other platform. I'll special case that I guess.

**Comment by hobu** [comment]
5802774f8c1f020b61a621c31e30578f6d9d4318 attempts to get the latest cmake which should fix this issue rather than the hack of trying to call out to `gdal-config`, which may or may not be installed depending on the platform. All of that logic should be in FindGDAL, which we recently abandoned in exchange for the official CMake variant.

**Comment by hobu** [comment]
Latest cmake appears to fix the Ubuntu issue. Adjust your dockerfile accordingly.

**Comment by nicolas-chaulet** [comment]
Works nicely! Thanks @hobu
