### ISSUE TITLE
E57 library bleeds symbols out of headers

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#2707]
The E57 reader/writer include files that force direct linking of the E57 support library on some platforms.  This shouldn't be necessary.

**Comment by norbertwenzel** [comment]
@abellgithub Are you talking about linking E57Format to the respective reader/writer tests? Or some different issue I do not fully understand yet?
I was trying to look into this but the more I did, the more I was unsure I was attacking the issue you were referring to. So I've done some basic cleanup (for a header that's never included except in the associated unit tests) in a [branch](https://github.com/PDAL/PDAL/compare/master...norbertwenzel:issue-2707) but could you clarify whether this is what you had in mind with this issue?

**Comment by abellgithub** [comment]
No users of PDAL should have to explicitly link the E57 library.  I think some of the tests do now.  I'd have to look back to give you more info.

**Comment by norbertwenzel** [comment]
The only uses of the E57 library I managed to `grep` outside the e57 reader/writer plugins where in their respective tests. This seems to be caused by the architecture of the tests, which are testing the PDAL reader/writer interfaces against the direct e57 implementation available in these plugins. So they have to link against the e57 library because the library is actively used in the test, not just because the reader/write include files force linking the library (which they previously did, but that dependency is removed in my branch).

It also seems that a lot of functions are explicitly exported from these plugins using the `PDAL_DLL` annotation just to use them in the tests. The number of such exported functions could be reduced (up to the bare PDAL `Reader/Writer/Streamable` interface functions) but this breaks compatibility with current interfaces (of which I'm not sure anybody uses these outside of the mentioned tests).

I removed most includes of E57 specifics from the headers, except from [`Scan.hpp`](https://github.com/PDAL/PDAL/blob/master/plugins/e57/io/Scan.hpp#L55) which directly returns a copy of an E57 library type (`e57::CompressedVectorNode`). Again I assume this is for testing only and no user including only `E57(Reader|Writer).hpp` would need to include `Scan.hpp` or link to the E57 library directly I believe.

So I will clean up my mess in the following days and make a PR for you to review. This PR will focus on removing the e57 internals from all headers where possible, without changing functions which I believe were intentionally exported from the shared library. This will remove the direct linking of the e57 library for the `pdal_io_e57_write_test`, but not the other test (which actively uses the library in test code).
