### ISSUE TITLE
issue with wkt polygon for readers.ept in PDAL 2.0.1

### ISSUE THREAD

**Issue by GGuidiRontani** [PDAL/PDAL#2744]
Hello, I'm facing an issue while using the readers.ept on PDAL 2.0.1 with Python 3.7.

The option "polygon" seems to return an unexpected argument. Here is the pipeline I tried to use this [pipeline](https://gist.github.com/DodoGab/0d4301f2c14904f0044d09d19c080327).

As written in issue [#2667](https://github.com/PDAL/PDAL/pull/2667#issuecomment-520494905) a way to skip it is to add a filter.crop with the wkt you want to use but I would prefer to avoid an unnecessary loading.

Regards

**Comment by connormanning** [comment]
I don't think that the EPT polygon functionality made it into the 2.0 release (that PR is milestoned as 2.1).  So I believe you'll have to build from source to get this functionality.

You can build PDAL master from source within the PDAL 2.0.1 Conda environment, which is probably the easiest method.

**Comment by connormanning** [comment]
Unrelated to your submitted issue, but your pipeline tagging doesn't look quite correct.  The tag `CROP` does not exist as input to the range filter, and it's odd that your LAS writer references the range filter instead of the preceding chipper filter, which makes it seem like the chipper filter goes unused.  If your pipeline is linear (as it appears it is meant to be) I recommend omitting the tagging entirely.

**Comment by DodoGab** [comment]
Thank you Connor, so I don't have to look forward to make it works properly on 2.0. I will try to milestone it on 2.1, as you advise, and will let you know when it is done.

Regarding the pipeline tagging issue, I posted a draft of my work while I was trying to get something from my pipeline. Basically, a `crop` is missing between the `ept` and the `chipper`.

About your recommendation, you right, it would be easier to avoid using taggs with this kinds of linears pipelines.

Thank you for your concern and your advises.
