### ISSUE TITLE
add readers.e57 and writers.e57 to pdal

### ISSUE THREAD

**Issue by AlbionS** [PDAL/PDAL#3130]
Hello Everyone,

Can somebody please explain how can I add readers.e57 and readers.e57.

I have the latest pdal version from docker hub and I would like to add the e57readers/writers inside the docker if it is possible. 
I've checked almost all of the versions of pdal on Docker hub and the readers.e57/writers.e57 are not added.

Is there any example how can I add them ? 

("**_Dynamic Plugin_**' !!?)
https://pdal.io/stages/readers.e57.html
https://pdal.io/stages/writers.e57.html 

Thank you very much for your help.
Best regards

**Comment by AlbionS** [comment]
@hobu 
Do you know who can help me to answer to this question ?

Is reader.e57 and writer.e57 free or do I need to pay anything to get that ?
I wasn't able to find anything that explains how to add that !

Best regards,

**Comment by hobu** [comment]
Github is not the place for these types of questions. It is for bugs and issue tracking. The[ mailing list ](https://pdal.io/community.html#mailing-list )is the appropriate place for these topics.

E57 support can be found by using the conda builds of PDAL. Otherwise, look through the source tree in `./scripts` for examples of how to build E57 support yourself.

**Comment by TaylorDale** [comment]
Thanks AlbionS, I use the Docker version as well and found this question when I was trying to figure out why E57 wasn't supported. Guess this is the answer for now, Docker version support would be great.
