### ISSUE TITLE
pcd: "Can't create dimension with invalid name '_'."

### ISSUE THREAD

**Issue by pglira** [PDAL/PDAL#3254]
**Describe the bug**
```
$ pdal info a.pcd
```
Output on command line is:
```
PDAL: Can't create dimension with invalid name '_'.
```
I have no idea why this happens... pcd file can be found here: https://www.dropbox.com/s/l122aywu7brpg9j/a.pcd?dl=0

**Expected behavior**
Report info about pcd file

**System/installation information:**
docker container "pdal/pdal"

```
$ uname -a
```
Linux f59ff9672d50 5.4.0-48-generic #52~18.04.1-Ubuntu SMP Thu Sep 10 12:50:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

```
$ pdal --version
```
pdal 2.1.0 (git-version: 176c4b)

**Comment by abellgithub** [comment]
This is a limitation in PDAL's PCD reader in dealing with binary data. The PCD binary format writes `_` in order to represent padding in the binary representation of the data as it is stored in memory. PDAL doesn't currently support this padded binary. You might try to write your data in ASCII format.

We would be interested in improvements to the current PcdReader that better handles binary data.

FYI, here is the header of your file:

```
# .PCD v0.7 - Point Cloud Data file format
VERSION 0.7
FIELDS x y z _ intensity t reflectivity ring _ noise _ range _
SIZE 4 4 4 1 4 4 2 1 1 2 1 4 1
TYPE F F F U F U U U U U U U U
COUNT 1 1 1 4 1 1 1 1 0 1 0 1 15
WIDTH 1024
HEIGHT 64
VIEWPOINT 0 0 0 1 0 0 0
POINTS 65536
DATA binary
```

**Comment by pglira** [comment]
Thank you for the quick reply!

No problem, I managed to translate the pcd file to an ascii file with cloud compare in the meanwhile. Just for the record, if somebody else encounters the same issue, I did it with

```
cloudcompare.CloudCompare -SILENT -O a.pcd -C_EXPORT_FMT ASC -ADD_HEADER -SAVE_CLOUDS FILE "a.asc"
```
