### ISSUE TITLE
Add a start location to readers.las

### ISSUE THREAD

**Issue by abellgithub** [PDAL/PDAL#3313]
An option to set a start position for `readers.las` would allow it to be used in a multi-threaded environment.

**Comment by danieldjewell** [comment]
What do you mean by a start location?

As far as I can tell, there are at least *some* aspects of the EPT Reader that are multithreaded... see below.

That said, I noticed that when accessing remote-hosted EPT datasets (e.g. over HTTP), things seem slow. 

I think this might be because:
* EPT datasets are broken up into a *LOT* of individual files (one of the USGS's LIDAR scans on Amazon S3 is 420,000+ files. (https://usgs-lidar-public.s3.amazonaws.com/PA_WesternPA_1_2019/ept.json)
* Requesting even a small subset of data by setting bounds still results in a **LOT** of HTTP requests. 
* The overhead on each individual HTTP request is pretty high. 
* It *appears* that the EPT Reader defaults to 4 threads in stream mode *regardless* of the setting of threads. (I think I'll double check on this and open a new issue if there isn't one already)

https://github.com/PDAL/PDAL/blob/d59be9b9bbd2d2341d55d9f16bca7433b0eeb16a/io/EptReader.cpp#L496-L516



---
### General Threading 

https://github.com/PDAL/PDAL/blob/d59be9b9bbd2d2341d55d9f16bca7433b0eeb16a/io/EptReader.cpp#L190-L195


https://github.com/PDAL/PDAL/blob/d59be9b9bbd2d2341d55d9f16bca7433b0eeb16a/io/EptReader.cpp#L442-L459

**Comment by abellgithub** [comment]
This ticket has nothing to do with the EPT reader. Please open another ticket if you have something to address about the EPT reader.

**Comment by abellgithub** [comment]
Fixed by #3339
