### ISSUE TITLE
Error installing pdal and python-pdal on conda

### ISSUE THREAD

**Issue by johnd-space** [PDAL/PDAL#3638]
Hello, 

I'm trying to install these two packages on my Vagrant box but it fails to load the `filter.python` when I do `pdal --drivers`
Been trying to figure this out for weeks but no luck.

This is the error I'm getting. 
`(PDAL Error) Can't load library /home/vagrant/miniconda/lib/python3.6/site-packages/pdal/libpdal_plugin_filter_python.so: Failed to load "/home/vagrant/miniconda/lib/python3.6/site-packages/pdal/libpdal_plugin_filter_python.so": libpdal_base.so.13: cannot open shared object file: No such file or directory(PDAL Error) Can't load library /home/vagrant/miniconda/lib/python3.6/site-packages/pdal/libpdal_plugin_reader_numpy.so: Failed to load "/home/vagrant/miniconda/lib/python3.6/site-packages/pdal/libpdal_plugin_reader_numpy.so": libpdal_base.so.13: cannot open shared object file: No such file or directory`

Any help would be appreciated.

**Comment by hobu** [comment]
for whatever reason your `python-pdal` package seems out of date relative to the `pdal` package that was installed. Please install into a clean conda environment and report back if you are still having trouble.

Also, it is unclear if Python 3.6 is actively supported at this point, so that may be an issue as well.

Create a new conda environment with:

```

conda create -n pdal-stuff -c conda-forge python=3.9 pdal python-pdal -y
conda activate pdal-stuff
python -m pdal
```
