### ISSUE TITLE
Build  Conda dev packages in Release mode

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#3709]
The Conda CI builder is building packages in Debug mode because of a default setting or something.

**Comment by hobu** [comment]
Related to this, our conda package at https://anaconda.org/pdal-master/pdal/files should have updated versioning to follow https://peps.python.org/pep-0440/ If we use dev version naming there it will be much easier for people to keep track of things python-style. Right now we end up overwriting versions because the version number is fixed.
