### ISSUE TITLE
Arbiter credentials should be controlled/set at the stage level

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#3792]
often for us, the read credentials and the write credentials are separate so we need to be able to control credentials at the stage level rather than for the entire pipeline

**Comment by hobu** [comment]
I talked to @connormanning and we decided that Arbiter needs to be updated to provide better profile support. That way you would easily be able to do something like this:

```
pdal translate \
    read-profile@s3://read-bucket/file.las \
    write-profile@s3://write-bucket/output.copc.laz
```

**Comment by msmitherdc** [comment]
so without a profile would use the default profile?

**Comment by connormanning** [comment]
Yes.  Arbiter currently works this way already with profiles under the hood, but requires explicit configuration in order to activate the non-default profiles.  This could be improved such that @hobu's command would work as-is with no other explicit configuration to PDAL, given that the credentials exist in the `~/.aws/credentials` file.
