### ISSUE TITLE
copc reader filters.hexbin without resolution but with threshold can result in spin without output

### ISSUE THREAD

**Issue by msmitherdc** [PDAL/PDAL#3809]
time docker exec -it pdal242 pdal info s3://grid-dev-publiclidar/angry_data/copc/4858_157957_M-33-58-B-c-2-3-3.copc.laz  --boundary

```
    ...
    "density": 10.94991532,
    "edge_length": 0,
    "estimated_edge": 18.20393681,
    "hex_offsets": "MULTIPOINT (0 0, -5.25502 9.10197, 0 18.2039, 10.51 18.2039, 15.7651 9.10197, 10.51 0)",
    "sample_size": 5000,
    "threshold": 15
  },
  "file_size": 66103105,
  "filename": "s3://grid-dev-publiclidar/angry_data/copc/4858_157957_M-33-58-B-c-2-3-3.copc.laz",
  "now": "2022-07-10T13:59:22+0000",
  "pdal_version": "2.4.1 (git-version: 006d06)",
  "reader": "readers.copc"
}

real	0m7.757s
```

time docker exec -it pdal242 pdal info s3://grid-dev-publiclidar/angry_data/copc/4858_157957_M-33-58-B-c-2-3-3.copc.laz --boundary  --filters.hexbin.threshold=1

```
real	131m31.262s
user	0m0.368s
sys	0m0.938s
```

**Comment by msmitherdc** [comment]
note that it was your recommendation to use threshold=1 with copc

**Comment by hobu** [comment]
> note that it was your recommendation to use threshold=1 with copc

I am a minor deity only in my own mind. Not in practice 😄 

You want threshold=1 for doing boundaries on COPC files because if you are reading at explicit resolutions, you are likely to only have a point or two for a given cell. You need that to count as positive space in that case. So while my recommendation for `filters.hexbin.threshold=1` was correct, so is the need to set an explicit `filters.hexbin.edge_size` or set `--filters.hexbin.sample_size=1000000` or larger to get a good sample of points outside of a single octree cell.

**Comment by hobu** [comment]
There's nothing to 'fix' here.
