### ISSUE TITLE
avg_pt_per_sq_unit In hexbin should be inverted 

### ISSUE THREAD

**Issue by chambbj** [PDAL/PDAL#3868]
I’m sure there is history here, but this seems to be computing the inverse of what it describes. Why is totalCount in the denominator?

https://github.com/PDAL/PDAL/blob/db4257e992daf0966b6d2f5681d88e914ed47bd7/filters/HexBinFilter.cpp#L260-L262

**Comment by hobu** [comment]
hmm, I don't remember, but I agree either the math or the description is wrong 😄 

Unfortunately the fix is to add another item that accurately describes what it is and leave the broken one but maybe update its description. We don't want to break external use of the thing now that people have accommodated its ~eccentricity~ completely backwards behavior.

**Comment by chambbj** [comment]
I don't think a fix (added field) is required. Updated description should be sufficient.

**Comment by hobu** [comment]
Implemented in https://github.com/PDAL/PDAL/pull/3901
