### ISSUE TITLE
Set CMake minimum version to 3.13+

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#3971]
This should allow us to throw out some conditionals in our CMake configuration and limit the amount of older stuff we purport to support but probably do not.

**Comment by j9ac9k** [comment]
No dog in this fight, but this is what [CMake availability is like on various Linux Platforms](https://pkgs.org/download/cmake)

Linux Distro vs. Available CMake

- Ubuntu 18.04 - CMake 3.10
- Ubuntu 20.04 - CMake 3.16
- Debian Strech - CMake 3.7 (stretch-backports has 3.13)
- Debian Buster - CMake 3.13 (buster-backports has 3.18)
- CentOS 7 - 2.8
- CentOS 8 - 3.20

Given Debian Stretch is already past EOL for LTS, Debian Buster just passed EOL, and Ubuntu 18.04 is about to pass into EOL LTS as well, I think a decent argument can be made to bump CMake up to 3.16 (instead of 3.13)

**Comment by hobu** [comment]
Completed in #4137
