### ISSUE TITLE
unbundle external libs (libeigen etc.)

### ISSUE THREAD

**Issue by t0b3** [PDAL/PDAL#4041]
**Describe the bug**
The bundling of external libs is considered v bad practice (unnecessary duplication) and is complicating maintenance for downstream (port fixes).

* Downstream strongly prefers pdal to drop the internal copies and the rely directly on those libs instead. monolithic bundling is considered bad implementation practice.

* Those dependancies can then be updated regularly so fixes i.e. this one for eigen on ppc will be included https://gitlab.com/libeigen/eigen/-/commit/9e0afe0f02173042ea03c10a6f896632fe84c6ff

Details see downstream issue on gentoo for ppc that leads to drop pdal entirely:
https://bugs.gentoo.org/865191

**Comment by abellgithub** [comment]
1) You can certainly submit an issue if PDAL doesn't compile out-of-the-box on any supported platform.

2) Packagers may well prefer unbundled libraries, but this doesn't make them better. Unbundling libraries brings uncertainty and change to an application. Very few libraries never change APIs and keeping up with changes is a chore. Worse, behavior can change when libraries are "fixed". Sometimes even "correct" fixes are bad in that they break expectations for users - this is not some rare occurrence. A bug in a library may well become expected behavior in an application that uses a library.

3) We have upgraded libraries when it has been deemed necessary, but controlling versions allows us to also test for changes that might impact users.

**Comment by t0b3** [comment]
Thanks for sharing this insights :+1: this helps to explain the why and how to deal with it downstream.
... and of course upgrading eigen would be a next step forward on the pathway :smile:

**Comment by Jean-Roc** [comment]
Hi, could some plugins such as E57 be switched to a git submodules ? For example, last week PR #4039 was fixed upstream in [nov 2022](https://github.com/asmaloney/libE57Format/pull/176)

**Comment by abellgithub** [comment]
I'm personally not a fan of git submodules, but others can speak up.

**Comment by hobu** [comment]
> Hi, could some plugins such as E57 be switched to a git submodules ?

If E57 vendored version needs a refresh, please ticket it.  In E57s case, it has gone through long periods of dormancy, and if we were using submodules we would have pointed to our own fork of it long ago. It is nice that it is active again, but the entire API got refactored in 3.0, and it is not clear what the consequences are for PDAL's usage of the library. A motivated E57 user needs to investigate and bring things forward.

As for submodules, I'm not a fan either. They are fragile, they add a complication to checkouts, and for libraries that are not part of wider packaging structures (like libe57 for conda forge, for example), we're stuck vendoring it anyway.

**Comment by hobu** [comment]
closing for now. If someone wants to take on the E57 update, please do so in a new PR.
