### ISSUE TITLE
Documentation for how to read a cloud point-by-point

### ISSUE THREAD

**Issue by oleg-alexandrov** [PDAL/PDAL#4245]
The developer documentation does not explain how to open an existing point cloud and read each point one by one for some user-specific purpose. I think this is a rather basic use case when integrating PDAL in a third-party application. 

This is different than https://github.com/PDAL/PDAL/pull/4238, where the goal was for user to create and write the cloud point by point.

I made this work by starting with GdalWriter, and stripping it to bare essentials. What is left is still a rather non-simple class that has to implement some functions from Streamable and also from FlexWriter (but for the latter as placeholders). 

If there is interest, I could provide a pull request with a self-contained example program, to be mentioned in the doc.

**Comment by abellgithub** [comment]
Pdal is not a point-by-ponit reader. We intentionally do not offer such an API. Of course you're welcome to modify the source code for your own use as you choose.

**Comment by oleg-alexandrov** [comment]
With LibLAS no longer developed and not having support for LAS 1.4, PDAL appears to be the only alternative, for reading LAS from C++. 

I did not modify any PDAL source code. Reading point-by-point is a matter of creating a little writer class that implements processing one point. 

Imagine saying GDAL is not in the business of reading Tif files.

**Comment by hobu** [comment]
> With LibLAS no longer developed and not having support for LAS 1.4, PDAL appears to be the only alternative, for reading LAS from C++.

[LASlib](https://github.com/LAStools/LAStools/tree/master/LASlib) from LAStools is a libLAS alternative. The licensing may be problematic for people, however. If you wish to take over the maintenance of libLAS to add what's needed, I would be very happy to hand you the keys.

>> how to open an existing point cloud and read each point one by one for some user-specific purpose

> Pdal is not a point-by-ponit reader. We intentionally do not offer such an API.

PDAL's design and approach was a reaction to the limitations of the point-by-point approach of libLAS 😁 I thought at one time @wenzeslaus had written a libLAS=>PDAL migration guide, but I can't seem to find it just now.

My worry about a point-by-point tutorial for PDAL is the next developer would follow it and come along and say "PDAL sucks for reading point-by-point because it has all this function call overhead". They're right, of course, but that's not the intended normal usage.

All that to say if you made a PR with the doc, I'd merge it 😄

**Comment by oleg-alexandrov** [comment]
> If you wish to take over the maintenance of libLAS to add what's needed, I would be very happy to hand you the keys.

I appreciate the highly generous offer!

I will work on a little program in the examples section. It will be useful at illustrating streaming in general.

**Comment by hobu** [comment]
> I appreciate the highly generous offer!

Free like a puppy 🐶 !

**Comment by oleg-alexandrov** [comment]
I looked into the PDAL reader code. Since the processOne() function is private, there doesn't seem an easy way of working with that.

It appears that the only way PDAL likes to work with is a table that connects a reader to a writer, and you have to create a writer to trick PDAL to do anything for you. 

This is what I had in mind for the user example. If you are not opposed to such a thing, I can write one, then can iterate on that.
