### ISSUE TITLE
Type of BSD licence

### ISSUE THREAD

**Issue by Sinan81** [PDAL/PDAL#4327]
I'm wondering what the precise license is. I see "BSD open source license" in LICENSE.txt, but that precise phrase isn't listed here:
https://spdx.github.io/spdx-spec/v2-draft/SPDX-license-list/#a1-licenses-with-short-identifiers
![image](https://github.com/PDAL/PDAL/assets/2924561/e49fa5ef-796b-4c36-98a1-e902fb93f95a)

**Comment by Sinan81** [comment]
related to https://github.com/spack/spack/pull/42714

**Comment by hobu** [comment]
I would say the project license is generally https://spdx.org/licenses/BSD-3-Clause-Attribution.html but there are some files that are individually licensed with different licenses due to them being vendored, etc.

The top-level license is https://github.com/PDAL/PDAL/blob/master/LICENSE.txt but if you look at cpp/hpp files, you can see they're each licensed and attributed individually.
