### ISSUE TITLE
CMake Option to build with system version of Eigen

### ISSUE THREAD

**Issue by enno-t** [PDAL/PDAL#4497]
In #4041 the desire (?) of some downstream packagers (like Gentoo) to unbundle libraries (like Eigen) has been expressed, though was rejected by PDAL due to concerns about API/ABI stability (for details see https://github.com/PDAL/PDAL/issues/4041#issuecomment-1537124492 and https://github.com/PDAL/PDAL/issues/4041#issuecomment-1538349781).

#4041 sought to debundle the libraries for all of PDAL, but what if a CMake option to  use the system version of Eigen was added, to enable downstream to use that if they desire (and an explicit message stating that this way of building PDAL is not supported by PDAL officially and any bugs must be shown with the bundled version in order to be valid?

The change itself is --- I'd argue --- minimally invasive to the CMake usage of PDAL (see https://github.com/enno-t/PDAL/commit/a4d9264d41e2687216e48249986012cd5fb2a74c).

Would such a change be acceptable?

**Comment by abellgithub** [comment]
Who benefits from this?

**Comment by enno-t** [comment]
> Who benefits from this?

Mainly downstream distributions that then don't have to carry unbundle patches ([like Fedora does](https://src.fedoraproject.org/rpms/PDAL/blob/rawhide/f/PDAL_unbundle.patch)).

**Comment by abellgithub** [comment]
And why would anyone unbundle Eigen?

**Comment by enno-t** [comment]
> And why would anyone unbundle Eigen? 

One reason is similar to the reason Eigen is bundled in the first place: consistency. While for PDAL this means knowing that a build was done with a specific version of Eigen, for downstream this means knowing that builds across the ecosystem are done with a consistent version of a library. Which also means that any (theoretical) patches would not need to be applied for every package that uses said library, but only once.

The other main reason I can think of is that the depencies are on the latest (packaged) version.

> What is the benefit to USERS or MAINTAINERS of this package?

The maintainers don't directly benefit from the bulk of this change*, unless of course there is a shift in views towards the topic, which is unlikely.

Users would have to be categorised into two (broad) categories:

-  users of PDAL-git
and
- users of PDAL-packages

with PDAL-git here meaning they use a PDAL version built directly from git/release sources with no patches changing behaviour (e.g. a patch that unbundles Eigen)

The first group has no direct benefits, while the second may have benefits. They'd arguably benefit from somewhat quicker package updates (due to downstream not having to recheck carried patches) and (though as a minor point) the knowledge that the version of Eigen used by PDAL is and behaves the same as other reverse-dependencies (e.g. blender).


* A minor point (though perhaps more a matter of style?) maintainers could benefit from the used PDAL_EIGEN_DIRS which sets the path to Eigen once and can then be reused, reducing maintenance if that path would change

**Comment by hobu** [comment]
> While for PDAL this means knowing that a build was done with a specific version of Eigen, for downstream this means knowing that builds across the ecosystem are done with a consistent version of a library. 

In the context of Eigen, specifically, this statement is incorrect. Eigen is compiled *into* PDAL at build time. It is not dynamically linked. There is no need to harmonize or align all of the vendored versions of Eigen in a packaging system. There is no value to doing this, and I would argue there's negative value to doing so because Eigen versions can change its behaviors and performance characteristics and PDAL has been sensitive to that in the past. 

Even if it compiles, it might not be ok. See https://github.com/microsoft/vcpkg/pull/32093 for an example where un-vendoring of nanoflann went awry and burned up a bunch of time. We get prickly about these kinds of pull requests because they change our team's area of responsibility to "any installed version of Eigen" instead of the specific version of Eigen we know to work. nanoflann, like Eigen, is compiled into PDAL and not dynamically linked, so the external exposure surface to the rest of the packaging system was zero. In the case of the attempt to un-vendor nanoflann, the episode only reinforced our project's stance on supporting such endeavors.

> A minor point (though perhaps more a matter of style?) maintainers could benefit from the used PDAL_EIGEN_DIRS which sets the path to Eigen once and can then be reused, reducing maintenance if that path would change

#4503 implements your patchset but sets `PDAL_VENDOR_EIGEN_DIR` instead of `PDAL_EIGEN_DIRS`

**Comment by dg0yt** [comment]
> compiled into PDAL and not dynamically linked

It must be made sure that it is *inlined*, or that symbols are renamed.
