### ISSUE TITLE
Support OGR feature selections for any geometry definitions 

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#4548]
## Problem

The definition of geometries for stages is inconsistent. Sometimes we take in `wkt` (which also transparently takes in GeoJSON but this isn't widely advertised), on some stages it is called`polygon`, on others `geometry`, and sometimes we support an `ogr` definition (like in [`readers.ept`](https://pdal.io/en/2.8.1/stages/readers.ept.html) and [`readers.copc`](https://pdal.io/en/2.8.1/stages/readers.copc.html)). It is all a bit messy and arbitrary.

## OGR Definition

The `ogr` definition is the most powerful approach, and it offloads the work of dealing with geometries to OGR. The following example shows how to select a geometry and do some reprojection to create a buffered geometry:

```
    "ogr": {
        "datasource": "../desired.geojson",
        "sql": "SELECT ST_Transform(ST_Union(ST_Buffer(ST_Transform(geometry, 3857), 300)), 4326) as geometry  from desired where HUC8 in ('02050304')",
        "options": {
            "dialect": "SQLITE"
        }
    }
```

![image](https://github.com/user-attachments/assets/e1b1a05a-a3c5-43bc-b7c7-9b6f85b1175d)

## Desire

It should be possible to pass in an `ogr` definition to PDAL stages for any option that would otherwise take in a geometry in WKT or GeeJSON. In almost all instances, this is what you want – figuring out how to manually transform a geometry into WKT or GeoJSON, maybe through some CLI operation, is fraught and annoying. Our current behavior also makes that activity happen outside of the context of a PDAL pipeline operation. It is much easier to point to some data, define a selection with [OGR SQL](https://gdal.org/en/latest/user/ogr_sql_dialect.html), manipulate and transform it as shown above, and let PDAL consume the geometry for its operations.

## Proposal

* Centralize the implementation of the `ogr` option
* Allow any `wkt` or `polygon` or `geometry` option to *also* take an `ogr` definition for geometries in addition to simple WKT or GeoJSON
* Enhance the `ogr` definition with any missing capabilities

**Comment by ibell13** [comment]
Here are all the stages that take geometry options right now:
 
Readers
- **CopcReader**: takes wkt/json polygon (_polygon_) and ogr json block (_ogr_)
- **EptReader**: takes wkt/json polygon (_polygon_) and ogr json block (_ogr_)
- **TIndexReader**: takes wkt/json polygon (_polygon_); also takes OGR SQL statement, but that's for filtering the tile index rather than the polygon you're selecting by. It might also be useful to clarify the distinction between the (_sql_) and (_where_) options.

Filters
- **CropFilter**: takes 2D/3D bounds (_bounds_), 2D/3D center point and radius (_point_ and _distance_), and geojson/wkt polygon(s) (_polygon_)
- **GeomDistanceFilter**: takes wkt/json geometry (_geometry_) and ogr json block (_ogr_)
- **OverlayFilter**: takes filename of OGR-readable datasource and SQL query separately (_datasource_ and _query_), as well as a bounding box to limit the query (_bounds_) and the column of the OGR data to read (_column_) (this could probably just be wrapped up into the SQL query AFAIK)
- **StraightenFilter**: takes LineStringZM as wkt/json (_polyline_)

Other
- **TIndexKernel**: merge subcommand filters the merged tile index with geojson/wkt (_polygon_) or a 3D bounding box (_bounds_). Pretty similar to readers.tindex, there might be common code that these could share.

All of the geometry options that support non-polygon and multiple polygon inputs are probably less suitable for an OGR block, but I thought I'd include them anyway. Some others, like readers.stac, take only a bounding box to filter the points, and I'm assuming the implementation isn't really the same there either.

**Comment by abellgithub** [comment]
I much prefer a standard format(s). Why would we tie ourselves to another software package that we may outgrow or decide we don't care for.

**Comment by hobu** [comment]
> I much prefer a standard format(s)

We currently have two – GeoJSON and WKT. They're both pretty crappy standards as far as that goes. Neither really supports 3D data, they get passed around as strings that can lose precision and must be marshaled externally to PDAL, and neither supports defining a coordinate system to go with it. We have a monkey-patched thing where we do stuff like add `/ EPSG:4326` to the end of the WKT or GeoJSON and make it be *invalid* WKT to satisfy our needs. I would say on the following standard formats front, we're failing quite miserably. 

GDAL is a hard dependency of PDAL. It supports sophisticated vector operations that users could leverage if we give them the convenience.
