### ISSUE TITLE
pdal info --boundary issue with disconetted point cloude areas

### ISSUE THREAD

**Issue by Esbern** [PDAL/PDAL#4563]
when running pdal info --boundary on a copc.laz file tile with disconnected point cloud areas see image

![pdal bug](https://github.com/user-attachments/assets/6b66d5fb-241a-499d-8d23-2f477a4a4845)

The boundary polygon only covers one of the areas (the grey on the image). The tool sees that there is more than one area to return and, therefore, returns a multi-polygon, although it only contains one ring.

    "boundary": "MULTIPOLYGON (((187950.88 6177311.7,188058.65 6177405.1,188031.71 6177545.1,187654.5 6177545.1,187654.5 6177451.7,187950.88 6177311.7)))",
    "boundary_json": { "type": "MultiPolygon", "coordinates": [ [ [ [ 6177311.728358150459826, 187950.877461319993017 ], [ 6177405.064179079607129, 188058.652383970009396 ], [ 6177545.067910459823906, 188031.708653309993679 ], [ 6177545.067910459823906, 187654.496424050012138 ], [ 6177451.732089539989829, 187654.496424050012138 ], [ 6177311.728358150459826, 187950.877461319993017 ] ] ] ] },

**Expected behavior**
expected to rings in the multipolygon

run as   
  "pdal_version": "2.8.1 (git-version: a06325)",
  "reader": "readers.copc"
}
on Windows installed with qgis (OSgeo4W)

**Comment by hobu** [comment]
The issue is `filters.hexbin` automatically "smooths" the geometries with `--filters.hexbin.smooth=true`. If you pass `--filters.hexbin.smooth=false` to your `pdal info` command, it will stop removing the additional bit of geometry. Additionally, it might be useful to make your edge size much smaller, like `--filters.hexbin.edge_size=10` or something to get a more resolved boundary. 

IMO none of the issues are bugs per se, and they're just the quirks of how the hexbin filter works in PDAL. There are options to control it more specifically, and if it is not sufficient, it is possible to go to the Python bindings and use whatever hull generation code you want over there.
