### ISSUE TITLE
PointStream complement to PointBuffer

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#754]
It is a frequent use case that folks use PDAL just for reading data. They might use one or two filters inline with operations, but that's it.

The current model requires reading the entire set of data into memory due to the fact that some filters like `filters.chipper` require the entire set to be able to begin computing. Our entire model currently satisfies this somewhat edge scenario. 

What if our API could default to supporting streaming operations when the entire list of intermediate filters (and maybe writers too) advertise that they can support it? Any filters would advertise their 
"streamability", and if any filter in a pipeline was not streamable, the stream `Stage::execute()` method would throw an exception.

```
Stage* reader = OpenReader(filename);
Stage filter = MakeReprojectionFilter; 
reprojection->setOptions(opts); 
reprojection->setInput(reader);
PointContextRef ctx;
filter->prepare(ctx);

PointStream strm(ctx);

// Throws if any stages cannot be read as a stream
strm = filter->execute(strm);

```

**Comment by gadomski** [comment]
:+1:

Just to make sure I'm understanding, "streamable" stages, e.g. filters, would have a method something like this?

```cpp
virtual void filter(PointStream& ptstream);
```

And the `PointStream` would support some an iterator interface that would let you do this?

```cpp
for (auto it = ptstream.begin(); it != ptstream.end(); ++it)
{
   *it; // should be a point reference or something?
}
```

**Comment by mpgerlek** [comment]
+1

This is similar to what we had back in the day, when we proceeded the data in continuously-emitted chunks/strips/blocks. Makes PDAL palatable for doing stuff like format-to-format translations (e.g. LAS to LAZ) or for reprojections (LAS/WGS84-to-LAS/somethingorother).

-mpg

On Feb 8, 2015, at 11:52 AM, Howard Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


It is a frequent use case that folks use PDAL just for reading data. They might use one or two filters inline with operations, but that's it.

The current model requires reading the entire set of data into memory due to the fact that some filters like filters.chipper require the entire set to be able to begin computing. Our entire model currently satisfies this somewhat edge scenario.

What if our API could default to supporting streaming operations when the entire list of intermediate filters (and maybe writers too) advertise that they can support it? Any filters would advertise their
"streamability", and if any filter in a pipeline was not streamable, the stream Stage::execute() method would throw an exception.

Stage* reader = OpenReader(filename);
Stage filter = MakeReprojectionFilter;
reprojection->setOptions(opts);
reprojection->setInput(reader);
PointContextRef ctx;
filter->prepare(ctx);

PointStream strm(ctx);

// Throws if any stages cannot be read as a stream
strm = filter->execute(strm);

**Comment by hobu** [comment]
Yes, the pendulum is swinging a bit...

The previous model didn't support `filters.chipper`, `filters.splitter` and the like without a ton of pretzel'ing. We've got good coverage of that now, but it needs to swing back a bit to support this very common case without too much hassle.

> And the `PointStream` would support an iterator interface that would let you do this?

```cpp
for (auto it = ptstream.begin(); it != ptstream.end(); ++it)
{
   // what if *it is a PointBuffer& of size=1 that's owned by the PointStream? Then no interface 
   // has to change
   *it; 

}
```

**Comment by c42f** [comment]
+1 this is great for the cases where applications want to control their own buffers.  May also help #726 by keeping the working set smaller.  If the iteration can be driven from user code the user application can control the read loop very simply.  For example, creating a progress bar in a GUI application is trivial with an iteration interface as proposed above.

For performance reasons, you may want to allow the stream to hold a `PointBuffer` a bit bigger than size 1 (eg let's say size 100) so that readers and filters can have a tight loop dealing with a bunch of points at once, and so that there's some chance that point attribute metadata handling can be hoisted out of the inner loop.  I think I have harped on about this before though ;-)

**Comment by mpgerlek** [comment]
(ideally *it would point to a handful of points, not just one, so as to lessen the overhead a bit)

-mpg



On Feb 8, 2015, at 6:41 PM, Howard Butler <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes, the pendulum is swinging a bit...

The previous model didn't support filters.chipper, filters.splitter and the like without a ton of pretzel'ing. We've got good coverage of that now, but it needs to swing back a bit to support this very common case without too much hassle.

And the PointStream would support an iterator interface that would let you do this?

for (auto it = ptstream.begin(); it != ptstream.end(); ++it)
{
   // what if *it is a PointBuffer& of size=1 that's owned by the PointStream? Then no interface
   // has to change
   *it;

}

**Comment by connormanning** [comment]
I was also thinking there would be some batched size of points, internally, hopefully configurable by some parameter on creation.  I think you could do it at the Reader/PointBuffer level, so that it's transparent to filters that only need sequential access.  My thoughts would be something like the RawPtBuf having some fixed buffer, filled with points up to capacity.  We could require incremental access to points, and then if a `getField` call asked for the upper boundary point index of that buffer, the next batch would be grabbed, and the current batch would be freed.  Not sure if that's possible with the current Stage/Filter setup, but it would be nice if it were as transparent as possible, hopefully internal to the Reader/PointBuffer.

**Comment by mpgerlek** [comment]
Everything old is new again :-)

-mpg



On Feb 9, 2015, at 10:23 AM, Connor Manning <notifications@github.com<mailto:notifications@github.com>> wrote:


I was also thinking there would be some batched size of points, internally, hopefully configurable by some parameter on creation. I think you could do it at the Reader/PointBuffer level, so that it's transparent to filters that only need sequential access. My thoughts would be something like the RawPtBuf having some fixed buffer, filled with points up to capacity. We could require incremental access to points, and then if a getField call asked for the upper boundary point index of that buffer, the next batch would be grabbed, and the current batch would be freed. Not sure if that's possible with the current Stage/Filter setup, but it would be nice if it were as transparent as possible, hopefully internal to the Reader/PointBuffer.

**Comment by abellgithub** [comment]
@c42f What do you mean by point attribute metadata?

**Comment by abellgithub** [comment]
If I'm going to do something about this, I need to understand what people want.  Is it sufficient to provide a pointer to the point data itself?  Do people want a pointer to the data for each dimension?  Do they want to be able to retrieve the data for each point pre/post scaling?  Do they want to be able to retrieve the data as a user-defined type, or just the natural type of the reader?  Who maintains the knowledge of the dimension type and how is that used?

**Comment by abellgithub** [comment]
Hearing silence, I went ahead and made some changes that are now in a branch called "stream" on github.  I think there are still some small changes I want to make to make things easier to use, but here's what I've done:

1) Created the ability to add a callback to the read() function that is implemented by Reader stages.  If a callback is registered with setReadCb(PointBuffer&, PointId), it will be called each time a point is read.

2) Added support for user-specified backing buffers.  You can now create a subclass of RawPtBuf and provide that to a PointContext so that data will get read from/written to that buffer instead of using the default implementation.  If you want to make a buffer that only stores a single point, or some set of points, you can do that easily.  You can also override the stored type of any dimension or indicate that you aren't going to store some dimensions at all.  You can also have PDAL write the read data directly into some unanticipated data store (say, some format of your own design, some weird database or something appropriate for rendering).

Putting these two things together using the existing interface, users can let PDAL do the reading and type-conversion of data while they can control selection and storage of what is read.

What's missing:

Right now there is only really support for a reader.  There is no easy way to "stream" data through subsequent stages or a pipeline.  I'm thinking about this.

Right now you always get data as PDAL views it - nominal values, rather than as represented in the source file (meaning scaling and offset are always applied when you get the data to store).  I don't think any change in this is merited, though perhaps some support to allow easy descaling might be appropriate.

I'm wondering if these changes might eliminate the need for the getPoint() interface that was recently added.

Feedback very welcome.

**Comment by abellgithub** [comment]
Changes made as stated above.  Closing until someone wants more.
