### ISSUE TITLE
GeoTransform set incorrectly in p2g plugin

### ISSUE THREAD

**Issue by matthewhanson** [PDAL/PDAL#762]
affected file:
plugins/p2g/io/P2gWriter.cpp

    double adfGeoTransform[6];
    adfGeoTransform[0] = m_bounds.minx;
    adfGeoTransform[1] = m_GRID_DIST_X;
    adfGeoTransform[2] = 0.0;
    adfGeoTransform[3] = m_bounds.maxy;
    adfGeoTransform[4] = 0.0;
    adfGeoTransform[5] = -1 * m_GRID_DIST_Y;

This results in an offset of a half pixel in the resulting images, since p2g is searching a radius around each increment starting at min_x, max_y.

The correct code should be

    double adfGeoTransform[6];
    adfGeoTransform[0] = m_bounds.minx - 0.5*m_GRID_DIST_X;
    adfGeoTransform[1] = m_GRID_DIST_X;
    adfGeoTransform[2] = 0.0;
    adfGeoTransform[3] = m_bounds.maxy + 0.5*m_GRID_DIST_Y;
    adfGeoTransform[4] = 0.0;
    adfGeoTransform[5] = -1 * m_GRID_DIST_Y;

This GeoTransform is passed into points2grid.   So either PDAL should not set the GeoTransform and let points2grid do it, or fix the one passed in.

I can issue a Pull Request, but since I'm new to PDAL I wanted to have one of the devs check this first.

**Comment by hobu** [comment]
@chambbj last touched this code, but he is out for about a week or so. I think the issue is the code originally just output ASCII grids, and we updated to output any GDAL-writeable datasource. It makes complete sense that it's now off by a half-pixel due to how GDAL views the world.

Please make the pull request and I'll happily merge it. Thanks for the contribution!

Howard
