### ISSUE TITLE
Add ScanAngle dimension

### ISSUE THREAD

**Issue by gadomski** [PDAL/PDAL#771]
Any reason why I wouldn't want to add a `ScanAngle` dimension, with some related smarts in the LasReader to convert `ScanAngle` to `ScanAngleRank`? Many writers produce scan angles with precision < 1°, and I can imagine several Writers and Filters that would want/use higher resolution scan angles.

If the idea is sound, I'll implement and open a PR.

cc @hobu

**Comment by abellgithub** [comment]
I don't understand.  It's all the same thing.  We just call it
ScanAngleRank because LAS was implemented first.

On Sun, Feb 22, 2015 at 9:58 AM, Pete Gadomski <notifications@github.com>
wrote:

> Any reason why I wouldn't want to add a ScanAngle dimension, with some
> related smarts in the LasReader to convert ScanAngle to ScanAngleRank?
> Many writers produce scan angles with precision < 1°, and I can imagine
> several Writers and Filters that would want/use higher resolution scan
> angles.
>
> If the idea is sound, I'll implement and open a PR.
>
> cc @hobu <https://github.com/hobu>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/771>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by abellgithub** [comment]
If the issue is that some other readers that don't have the field
predefined, but instead call it "ScanAngle" as text in the schema, that can
be handled by mapping it in the Dimension header file.

On Sun, Feb 22, 2015 at 9:58 AM, Pete Gadomski <notifications@github.com>
wrote:

> Any reason why I wouldn't want to add a ScanAngle dimension, with some
> related smarts in the LasReader to convert ScanAngle to ScanAngleRank?
> Many writers produce scan angles with precision < 1°, and I can imagine
> several Writers and Filters that would want/use higher resolution scan
> angles.
>
> If the idea is sound, I'll implement and open a PR.
>
> cc @hobu <https://github.com/hobu>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/771>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by gadomski** [comment]
I asked for the change because I got a little befuddled while developing a new reader. I went looking for a dimension called `ScanAngle` to hold a float coming out of the reader and I found `ScanAngleRank`. When I checked the las spec for what `ScanAngleRank` meant, it didn't match with what my new reader provides.

I'd be in favor of renaming `ScanAngleRank` to `ScanAngle` to minimize confusion for new driver developers, and trust the las writer to convert a higher-precision `ScanAngle` to the integer value the writer needs. I think the las writer does this conversion already, though it may [truncate rather than round](https://github.com/PDAL/PDAL/blob/master/io/las/LasWriter.cpp#L575) (correct me if I'm wrong there).

I worry about putting some sort of alias between `ScanAngle` and `ScanAngleRank` — seems like a recipe for dimension proliferation to me.

**Comment by abellgithub** [comment]
On Sun, Feb 22, 2015 at 11:58 AM, Pete Gadomski <notifications@github.com>
wrote:

> I asked for the change because I got a little befuddled while developing a
> new reader. I went looking for a dimension called ScanAngle to hold a
> float coming out of the reader and I found ScanAngleRank. When I checked
> the las spec for what ScanAngleRank meant, it didn't match with what my
> new reader provides.
>
I think it does match what your reader provides, it just doesn't have the
same precision, right?

> I'd be in favor of renaming ScanAngleRank to ScanAngle to minimize
> confusion for new driver developers, and trust the las writer to convert a
> higher-precision ScanAngle to the integer value the writer needs. I think
> the las writer does this conversion already, though it may truncate
> rather than round
> <https://github.com/PDAL/PDAL/blob/master/io/las/LasWriter.cpp#L575>
> (correct me if I'm wrong there).
>
You really don't need to worry about some reader other than yours.  If your
reader wants to add a dimension called "ScanAngle," that's fine, but I
think it MEANS the same thing as "ScanAngleRank" that comes from LAS files,
so it seems unfortunate and unnecessary to create another dimension.  I'm
not a fan of renaming things.  More data is stored in LAS than any other
format and more people are therefore familiar with the name
"ScanAngleRank".  I think dropping the "rank" from the name is more clear
(since it doesn't seem to add anything), but it is what it is.

We always round, we don't truncate.

> I worry about putting some sort of alias between ScanAngle and
> ScanAngleRank — seems like a recipe for dimension proliferation to me.
>
I think this is inevitable given that people define their own schema and
own names in many formats.  Even LAS with extra bytes does this.  Making it
easy for people to mingle files with different dimension name but
equivalent meaning seems beneficial.

-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by gadomski** [comment]
> We always round, we don't truncate.

Excellent.

> I think this is inevitable given that people define their own schema and
own names in many formats.  Even LAS with extra bytes does this.  Making it
easy for people to mingle files with different dimension name but
equivalent meaning seems beneficial.

I guess I'll quibble a bit here. When I'm writing a new reader, for instance, I'm going to do my best to map my reader's dimensions onto the existing PDAL dimensions to try to keep things simple. Sure, there will be times I'll have to create something new, but it seems to me that the scan angle question is kind of a special case. `ScanAngle` can be thought of as a superset of `ScanAngleRank`, so `ScanAngle` could be considered the more general case that absorbs all of the `ScanAngleRank`s.

However, I do hear you that las is by far the most common format, so it makes sense to support the las format verbatim. Conceding that point, I think an alias is the way to go, mapping `ScanAngle` -> `ScanAngleRank`; this should lower new driver friction by a bit.

*Aside for fun Github linking: this issue is related to #481, and more generally the problem of dimension proliferation/addition/definition.*

**Comment by gadomski** [comment]
Fixed by 2a3bf64
