### ISSUE TITLE
Have travis run pgpointcloud tests

### ISSUE THREAD

**Issue by strk** [PDAL/PDAL#839]
It seems to me that Travis is not running pgpointcloud tests.
I know because it gave a green on #837 while still known to be broken.

**Comment by strk** [comment]
To confirm pgpointcloud is not tested: https://travis-ci.org/PDAL/PDAL/jobs/54878637#L1323-L1333

**Comment by strk** [comment]
On my local build, where PGPOINTCLOUD support is built, the "PostgreSQL" package is listed under "REQUIRED" packages that have been found. On travis, it is still listed as "found", but under the "OPTIONAL" packages. What's the deal ?

**Comment by gadomski** [comment]
I believe it is because we actually search for PostgreSQL in [two](https://github.com/PDAL/PDAL/blob/master/CMakeLists.txt#L139) [spots](https://github.com/PDAL/PDAL/blob/master/cmake/postgres.cmake#L5). The first is to auto-enable (or disable) PostgreSQL support, the second is to ensure that PostgreSQL is available if the user has asked for it.

Since the first `find_package` is non-required, PostgreSQL will show up as optional if the plugin [is not enabled](https://github.com/PDAL/PDAL/blob/master/scripts/ci/script.sh#L36).

**Comment by strk** [comment]
I actually found the exact spot where PGPOINTCLOUD is _explicitly_ disabled:
https://github.com/PDAL/PDAL/blob/master/scripts/ci/script.sh#L36

**Comment by strk** [comment]
For the record, I'm using PR #846 for testing enabling pgpointcloud tests  in travis

**Comment by strk** [comment]
@gadomski indeed enabling PGPOINTCLOUD makes it listed as REQUIRED: https://travis-ci.org/PDAL/PDAL/jobs/55809540#L1897

It also shows the additional message I was missing before:
https://travis-ci.org/PDAL/PDAL/jobs/55809540#L1865
