### ISSUE TITLE
StageFactory not thread-safe

### ISSUE THREAD

**Issue by connormanning** [PDAL/PDAL#853]
StageFactory's constructor seems to assume that it will only occur once, but that is not enforced - subsequent calls will try to reinitialize the singleton PluginManager.

**Comment by abellgithub** [comment]
This makes no sense to me.  How is the plugin manager getting initialized more than once?  Don't know that having to access things through the global environment is appealing.

**Comment by connormanning** [comment]
Make multiple StageFactory instances initializes the PluginManager multiple times.

**Comment by hobu** [comment]
PluginManager was static'd too, and we want to centralized static'd stuff in GlobalEnvironment so threading folks at least have a chance.

**Comment by abellgithub** [comment]
I get that PluginManager was static.  It's localized and contained in the
StageFactory, which makes a lot of sense.  I don't understand how/why
PluginManager would be initialized more than once.  How can it?  A static
in a function is only initialized the first time execution runs through the
function.  Normally this is done to defer initialization until first access
and save start-up cost.  Maybe that's not important, but still seems better
to stick it in StageFactory as a static and create at start than to stick
it in GlobalEnvironment.

On Wed, Apr 1, 2015 at 8:04 AM, Howard Butler <notifications@github.com>
wrote:

> PluginManager was static'd too, and we want to centralized static'd stuff
> in GlobalEnvironment so threading folks at least have a chance.
>
> > On Apr 1, 2015, at 7:59 AM, Connor Manning <notifications@github.com>
> wrote:
> >
> > Make multiple StageFactory instances initializes the PluginManager
> multiple times.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PDAL/PDAL/issues/853#issuecomment-88472700>.
>



-- 
Andrew Bell
andrew.bell.ia@gmail.com

**Comment by abellgithub** [comment]
After some discussion, it seems the issue is that things blow up if multiple StageFactory objects get created in a multi-threaded environment.  We aren't really thread-safe, so this isn't surprising, but I *think* that the fix is to put some locks around some of the members of the singleton PluginManager.

**Comment by hobu** [comment]
@chambbj do you remember why you had PluginManager be static in the first place? Were you intending that multiple StageFactory instances share it?

> Probably also best to move the initialization of PluginManager to start-time (probably by making it a static member of StageFactory) to avoid another mutex in getInstance().

What do you mean by start-time? Start-time of StageFactory?

That said, I think that PDAL should do its best to put any read-write static'd things in GlobalEnvironment so that people wanting to do thread stuff at least have a chance. This also might make it a big enough PITA so that people don't make static things very often.

**Comment by abellgithub** [comment]
Start-time = before the program execution begins.

I still think that it's better to hide things if possible, and this makes it so that only the StageFactory needs to know about the PluginManager, though I'll have to look at the KernelFactory code.  It could have its own PluginManager and that would be fine, I think.  Putting things in GlobalEnvironment opens access up to everyone and means you have to access one singleton through another singleton and you bleed GlobalEnvironment into code where it wouldn't be necessary.  Just adding an extra singleton layer doesn't really add much of value.  The only reason to do that that I can think of is that you can control initialization order.  In this case, I don't think that's an issue.  I believe that PluginManager is self-contained.

**Comment by hobu** [comment]
Ok. Can you close #858 and fix this up how your describe? We do want to support being thread safe and this issue is a definite blocker on that front.

**Comment by chambbj** [comment]
@hobu I wouldn't read too much into my design choices. I'm sure this is just how it was done in the article I ripped it from. It does make sense to me that there be only one, shared PluginManager. In theory,  any plugin can be loaded, re-loaded, or unloaded individually. It's the job of the PluginManager to keep track of what is loaded and to unload via the destructor if it hasn't been unloaded elsewhere (in our adaptation, I believe they are always handled this way).

@abellgithub Yes, this is shared with the KernelFactory. The PluginManager doesn't really care about Stage vs. Kernel. It just enforces that the Stage and Kernel plugins adhere to the plugin framework and does some bookkeeping along the way.

I have no opposition to somebody making this more thread-safe. I definitely did not have that in mind when I was implementing it.

**Comment by abellgithub** [comment]
Resolved.
