### ISSUE TITLE
BufferReader and StatsFilter and PointTable

### ISSUE THREAD

**Issue by mpgerlek** [PDAL/PDAL#890]
https://gist.github.com/mpgerlek/7999df1d46290962d69c

This file demonstrates an interesting thing about the BufferReader and the Stats filter: when executed with a "new" output table the stats metadata is incorrect, but when executed against the "input" table (as the BufferReader unit test does) the metadata is correct.

This was unexpected to me, as the convention in other unit tests is to create a "new" table as the output target (see, for example, SplitterTest).

(It is also, perhaps, worth asking why you need to pass the table to both the prepare() and execute() functions: what happens if different tables are passed in?)

**Comment by abellgithub** [comment]
In almost all cases there is no reason to use more than one PointTable.

The PointTable is a table of points that are arranged according to the layout that you provide (the actual arrangement of the data in the Table is an implementation detail, just as it would be in a relational database table).  There is no provision for points added to one PointTable to migrate to another point table and there is no provision to automatically take the layout (dimensions) from one PointTable and use them in another point table, though you're free to subclass BaseTable (rather than PointTable) to get this effect.

In your code, the outputTable has no dimensions, so any operations that use the table will essentially do nothing.

I looked at SplitterTest and only see a single PointTable in use, so I'm not sure what you're referring to.

If you call someFilter.execute(pointTableA) without having first called someFilter.prepare(pointTableA), the results are undefined.  It is sometimes useful to call prepare(), but never call execute() and it's rarely useful to call prepare() once followed by multiple calls to execute(), but there are cases where it has been done.

**Comment by mpgerlek** [comment]
_There is no provision for points added to one PointTable to migrate to another PointTable and there is no provision to automatically take the layout (dimensions) from one PointTable and use them in another PointTable_

Ah! I had assumed that was explicitly supported, because I misunderstood the intent behind the prepare() and execute() steps (and am still in the (now very old) PDAL pipeline mindset). I get it now, thank you.

I'd suggest that, if execute() is required to take exaclty the same table as prepare(), that the parameter to execute() be removed and let it be carried across internally. This would make the API's intent clear.

**Comment by mpgerlek** [comment]
(Yes, I know SplitterTest only uses one table. I was referring to the idiom of declaring the table just before calling execute() against it, an idiom SplitterTest uses. If one doesn't understand how the table is used by the pipeline steps and uses that same idiom with BufferReader, the result may be unexpected.

I admit BufferReader is a weird case, though, precisely because it requires a table to initialize it, unlike most (all?) other readers.)
