### ISSUE TITLE
MetadataNode access sugar

### ISSUE THREAD

**Issue by hobu** [PDAL/PDAL#938]
Traversing and finding stuff in MetadataNode is laborious and a bit of a hassle. It would be convenient too have some accessor sugar that allows you to make calls like (or something like it): 

```
MetadataNode m2 = m.findChild("stats:X:minimum");
```

**Comment by abellgithub** [comment]
We already have this particular syntax.  The issue (I think) is obtaining nodes based on siblings.

**Comment by abellgithub** [comment]
The issue here is that we want to find a sibling node based on a value.  I think this is kind of hard for a tree-based structure in a simple way.  What seems most reasonable is for the tree to be structured in a way that allows access by keys, rather than by values.  Is it too late to rearrange our stats output so that this works out of the box?  Otherwise, we'd probably be faced with something like:
`m.findChild("stats:name=X;minimum")` where '=' indicates a value match and ';' indicates a sibling node.  Maybe this doesn't seem too bad, but if you start doing floating value matches or some such, things just get ugly.  To me, that we're having trouble with this means the tree arrangement needs to be rethought.
